//------------------------------------------------------------------------
//	Storage.script
//	
//	Scripted events for the Storage1 level.
//	Last major modifications done Nov 3
//
//  FIXME: The opening pod-crash needs fixing in this script
//  FIXME: The fire doors need to be their own func_firedoor, not this current style.
//
//	mrenner, cbordwell, jshepard, jdischler
//	Nov 3
//------------------------------------------------------------------------

//Dmg spinning rings flag
float spinRings = 1;

namespace map_storage1
{

//-------------------------------------------------------
// podName - the entity name of a func_mover...must be targetted at a destination entity
// moveTime - how long it will take to move to the desired location
// wait - how long to wait after the move before returning.
//
// ...any targets of the destination entity are triggered when the destination position is 
//		reached (could be an explosion effect, for example)
// NOTE: the mover entity is recycled...meaning it can be triggered multiple times
//-------------------------------------------------------
void doAmbientDropPod( entity eMover, float moveTime, float waitTime )
{
	if ( !isValidEntity(eMover))
	{
		return;
	}

	// get's first target as the destination
	if ( eMover.numTargets() < 1 )
	{
		//		sys.println("doAmbientDropPod: mover must have a target, which is the destination of the crash" );
		sys.waitFrame();
		return;
	}

	// use burn or the normal trail
	entity eFxTrail = $func_fx_pod_burn_sm;
	if ( sys.random(1)>0.5)
	{
		eFxTrail = $func_fx_pod_trail_sm;
	}
	eFxTrail.setWorldOrigin( eMover.getWorldOrigin());
	eFxTrail.setAngles( eMover.getAngles());
	eFxTrail.bind(eMover);

	entity eDest = eMover.getTarget(0);

	// crash it in
	eMover.show();

	eMover.time( moveTime);
	eMover.moveTo( eDest );
	sys.waitFor( eMover );

	// use any targets
	eDest.activateTargets(eMover);

	// recycle it
	eMover.hide();
	eMover.restorePosition();

	eFxTrail.unbind();
	eFxTrail.restorePosition();

	sys.wait(waitTime);
}

// Um handles more than just the elevator crash pods for now
void doAmbientElevatorCrashPods()
{

	while(1)
	{
		doAmbientDropPod( $ambient_droppod_1, 5, 6 );
		doAmbientDropPod( $skybox_ambient_droppod_2,6,4);
		doAmbientDropPod( $ambient_droppod_2, 5, 6 );
		doAmbientDropPod( $skybox_ambient_droppod_3,6,4);
		doAmbientDropPod( $ambient_droppod_3, 5, 5 );
		doAmbientDropPod( $skybox_ambient_droppod_1,5,3);
	}
}

void mainBeamTop()
{
	while(1)
	{
		//sys.trigger($beamBlastInf);

		sys.trigger($beamBlastLight);
		$beamBlastFlare.show();
		sys.trigger($distortTop);
		setNewTimes( $beamBlast, 3 , 0 , 0 );
		$beamBlast.moveTo( $func_static_13388 );
		sys.waitFor($beamBlast);
		
		sys.trigger($beamBlastFx);	// off
		$beamBlastFlare.hide();		
		sys.trigger($beamBlastLight);
		sys.trigger($distortBottom);		
		
		setNewTimes( $beamBlast, .1 , 0 , 0 );
		$beamBlast.moveTo( $target_null_82 );
		sys.waitFor($beamBlast);
		sys.wait(.1);

		sys.trigger($beamBlastLight);
		sys.trigger($beamBlastFx);	// on
		$beamBlastFlare.show();
		setNewTimes( $beamBlast, 5 , 0 , 0 );
		$beamBlast.moveTo( $target_null_83 );
		sys.waitFor($beamBlast);

		sys.trigger($beamBlastFx);	// off		
		$beamBlastFlare.hide();		
		sys.trigger($beamBlastLight);
		setNewTimes( $beamBlast, .1 , 0 , 0 );
		$beamBlast.moveTo( $target_null_81 );
		sys.waitFor($beamBlast);
		sys.wait(1.4);
		sys.trigger($beamBlastFx);	// on
	}
}

void moveTsdAngle(entity tsd, entity begin, entity end)
{
	//tsd.becomeNonSolid();
	
	while(1)
	{
		sys.wait( .1 + sys.random(.2) );		
		// set move time and show
		tsd.accelTime(.1);
		tsd.time(.4);	
		tsd.show();
				
		//move to end
		tsd.moveTo(end);	
		sys.waitFor(tsd);
		
		// hide and move to start
		tsd.hide();
		tsd.time(.1);
		tsd.moveTo(begin);	
		sys.waitFor(tsd);	
	}
}
void moveTsdFast(entity tsd, float units)
{
	while(1)
	{
		sys.wait( .1 + sys.random(.2) );		
		// set move time and show
		tsd.accelTime(.1);
		tsd.time(.4);	
		tsd.show();
				
		//move to end
		tsd.move( UP, units );	
		sys.waitFor(tsd);
		
		// hide and move to start
		tsd.hide();
		tsd.time(.1);
		tsd.move( DOWN, units );	
		sys.waitFor(tsd);	
	}
}
void moveTsdTall(entity tsd, float units)
{
	while(1)
	{
		sys.wait( .1 + sys.random(.2) );		
		// set move time and show
		tsd.accelTime(.1);
		tsd.time(.75);	
		tsd.show();
				
		//move to end
		tsd.move( UP, units );	
		sys.waitFor(tsd);
		
		// hide and move to start
		tsd.hide();
		tsd.time(.1);
		tsd.move( DOWN, units );	
		sys.waitFor(tsd);	
	}
}


void moveTsdSouth(entity tsd, float units)
{
	while(1)
	{
		sys.wait( .1 + sys.random(.2) );		
		// set move time and show
		tsd.accelTime(.1);
		tsd.time(.4);	
		tsd.show();
				
		//move to end
		tsd.move( SOUTH, units );	
		sys.waitFor(tsd);
		
		// hide and move to start
		tsd.hide();
		tsd.time(.1);
		tsd.move( NORTH, units );	
		sys.waitFor(tsd);	
	}
}

void envTsd(entity tsd)
{
	while(1)
	{
		playAnimWait( tsd, ANIMCHANNEL_ALL, "shockstart");
		tsd.playCycle(ANIMCHANNEL_ALL, "shockloop");
		sys.wait( 5 + sys.random(2) );	
		playAnimWait( tsd, ANIMCHANNEL_ALL, "shockstop");
		playAnimWait( tsd, ANIMCHANNEL_ALL, "storage");
	}
}

//-------------------------------------------------------------
// void openFireDoor(entity doorLeft, entity doorRight, entity hinge)
//
// Opens a fire door. Make sure you have the left and right doors named correctly!
// The hinge should be a target null that is at the top of and inbetween the two doors.
// NOTE: the sound shader must be cached in main()
//
// JShepard, jdischler | May 04
//-------------------------------------------------------------
void openFireDoor(entity doorLeft, entity doorRight, entity hinge)
{
	//set the time up
	doorLeft.time(.5);
	doorRight.time(.5);
	
	//bind 'em to the hinge
	doorLeft.bind(hinge);
	doorRight.bind(hinge);

	//rotate both the left and right doors
	hinge.startSoundShader( "storage_firedoor_open", SND_CHANNEL_ANY );
	doorLeft.rotateOnce('0 0 -90');
	doorRight.rotateOnce('0 0 90');

	sys.waitFor(doorLeft);

	//unbind
	doorLeft.unbind();
	doorRight.unbind();
}
//-------------------------------------------------------------
// void closeFireDoor(entity doorLeft, entity doorRight, entity hinge)
//
// Closes a fire door. Make sure you have the left and right doors named correctly!
// The hinge should be a target null that is at the top of and inbetween the two doors.
// NOTE: the sound shader must be cached in main()
//
// JShepard, jdischler | May 04
//-------------------------------------------------------------
void closeFireDoor(entity doorLeft, entity doorRight, entity hinge)
{
	//set the time up
	doorLeft.time(.5);
	doorRight.time(.5);
	
	//bind 'em to the hinge
	doorLeft.bind(hinge);
	doorRight.bind(hinge);

	//rotate both the left and right doors
	hinge.startSoundShader( "storage_firedoor_open", SND_CHANNEL_ANY );
	doorLeft.rotateOnce('0 0 90');
	doorRight.rotateOnce('0 0 -90');

	sys.waitFor(doorLeft);

	//unbind
	doorLeft.unbind();
	doorRight.unbind();
}

/*------------------------------------------------------------------------
Repair bot banging into the door -Chad
------------------------------------------------------------------------*/

void firebot_1()
{
	sys.trigger($firebot_1);
	aiScriptedAnimLoop ( $firebot_1, "storage", 0 );
	sys.trigger($func_fx_87);
}

void firedoor02()
{
	openFireDoor($fire_door_lf_02, $fire_door_rt_02, $tgt_hinge_2);
	sys.wait(5);
	closeFireDoor($fire_door_lf_02, $fire_door_rt_02, $tgt_hinge_2);
}

void firedoor03()
{
	openFireDoor($fire_door_lf_03, $fire_door_rt_03, $tgt_hinge_3);
	sys.wait(5);
	closeFireDoor($fire_door_lf_03, $fire_door_rt_03, $tgt_hinge_3);
}

void firedoor04()
{
	openFireDoor($fire_door_lf_04, $fire_door_rt_04, $tgt_hinge_4);
	sys.wait(5);
	closeFireDoor($fire_door_lf_04, $fire_door_rt_04, $tgt_hinge_4);
}

void firedoor05()
{
	openFireDoor($fire_door_lf_05, $fire_door_rt_05, $tgt_hinge_5);
	sys.wait(5);
	closeFireDoor($fire_door_lf_05, $fire_door_rt_05, $tgt_hinge_5);
}

void firedoor06()
{
	openFireDoor($fire_door_lf_06, $fire_door_rt_06, $tgt_hinge_6);
	sys.wait(5);
	closeFireDoor($fire_door_lf_06, $fire_door_rt_06, $tgt_hinge_6);
}

void buriningGrunt()
{
	aiScriptedAnimWait($fireGrunt, "on_fire", 4, 1);	
	$fireGrunt.kill();
}

//------------------------------------------------------------------------
// Firebot putting out a fire
//
// jdischler, Chad, mrenner | Jan 2005
//------------------------------------------------------------------------
void killfire_1()
{
	thread openFireDoor($fire_door_lf_01, $fire_door_rt_01, $tgt_hinge_1);
	
	// move the firebot into place...in this case, the 'stuck' spot really isn't stuck,
	//	but its in a handy location, so I'm reusing this target_null.

	aiScriptedMoveWait( $firebot_1, $targetFirebot_dest, 20, 0 );

	aiScriptedMoveWait( $firebot_1, $targetFirebot_dest1, 20, 0 );
	aiScriptedFace( $firebot_1, $fxLargeFire, 1 );

	sys.wait(2);	
	aiScriptedAnimLoop( $firebot_1, "repair", 0 );
	
	// let him spray a bit, then replace the big fire with a custom effect that goes
	//	out in stages
	//sys.wait(2);	
	sys.trigger($fxLargeFire);	// turn it off
	sys.trigger($fxPutOutFire);	// turn it on
	sys.trigger($func_fx_109);	// turn it off

	// transition local lighting
	$firebotFireLight.fadeOutLight(8);	// fire light should fade out...but..
	//	$replacementLight.fadeInLight(8);	// replace it with another light so we don't have blackness
	
	//	sys.wait(9);	//	mrenner

	sys.wait(2);
	
	// pain, pain...go away
	$fireHurtBrush1.remove();
	$fireHurtBrush1_small.remove();
	sys.wait(2);

	aiScriptedAnimLoop( $firebot_1, "idle_to_run", 10 );
	
	// that job is done, then leave the scene	
//	aiScriptedMoveWait( $firebot_1, $firebot_removeTarget, 5, true );

	aiScriptedMoveWait( $firebot_1, $targetFirebot_dest, 20, 0 );
	aiScriptedMoveWait( $firebot_1, $firebot_removeTarget_1, 30, 0 );
	$firebot_1.remove();
}

//------------------------------------------------------------------
// Crash a pod into one of the rooftop machines, spawn some effects
//	and create an extra bit of cover
//
// jdischler | Jan 2005
//------------------------------------------------------------------
void doRooftopCrashPod()
{
	// start the sound..it's not bound at this point
	sys.wait(6.5);
	sys.trigger($speaker_incoming);

	sys.wait(2);

	// bind the sound and the smoke to the pod and bring the whole lot in for a big crash
	$incomingPod.show();
	$speaker_incoming.bind($incomingPod);
	$fx_podDropTrail.bind($incomingPod);
	sys.trigger($fx_podDropTrail);
	$incomingPod.speed(2300);
	$incomingPod.moveTo($target_podDest);

	sys.waitFor($incomingPod);

	// pod go boom
	sys.trigger($fx_machineImpactExplosion);
	sys.trigger($speaker_machineImpactExplosion);
	sys.wait(0.2);

	// switch the objects all around
	$incomingPod.remove();
	sys.trigger($fx_podDropTrail);
	$machineToBeHit.remove();
	$crunchedMachine.show();
	sys.trigger($fx_crunchedMachine);
	sys.trigger($fireHurtBrush_2);

	// wait a bit then throw up a secondary explosion
	// NOTE: not sure I like this all that much?  Maybe?
	sys.wait(8.0 + sys.random(10));
	sys.trigger($fx_secondaryExplosion);
}

//------------------------------------------------------------------
// Crash a pod into one of the rooftop towers, spawn some effects
//	 TODO: swap in a smashed version of the tower?
//
// jdischler | Jan 2005
//------------------------------------------------------------------
void doRooftopTowerCrashPod()
{
	// start the sound..it's not bound at this point
	sys.wait(6.5);
	sys.trigger($speaker_incoming_1);

	sys.wait(1);

	// bind the sound and the smoke to the pod and bring the whole lot in for a big crash
	$incomingPod_1.show();
	$speaker_incoming_1.bind($incomingPod_1);
	$fx_podDropTrail_1.bind($incomingPod_1);
	sys.trigger($fx_podDropTrail_1);
	$incomingPod_1.speed(2300);
	$incomingPod_1.moveTo($target_podDest2);

	sys.waitFor($incomingPod_1);

	// pod go boom
	sys.trigger($fx_towerImpactExplosion);
	sys.trigger($speaker_towerImpactExplosion);

	// switch the objects all around
	$incomingPod_1.remove();
	sys.trigger($fx_podDropTrail_1);

	// TODO: swap in a smashed version of the tower?
}

/*------------------------------------------------------------------------
Doors open and fire goes out once bridge is lowered -Chad
------------------------------------------------------------------------*/

void open_path()
{
	openFireDoor($fire_door_lf_07, $fire_door_rt_07, $tgt_hinge_7);
	openFireDoor($fire_door_lf_08, $fire_door_rt_08, $tgt_hinge_8);
//	sys.trigger($monster_repair_bot_1);
//	sys.trigger($monster_repair_bot_2);
	sys.trigger($func_fx_71);
	sys.trigger($func_fx_61);
}

/*------------------------------------------------------------------------
Laser Coupling -Chad
------------------------------------------------------------------------*/

void laser_coupling()
{
	$laser_coupling_1.playCycle(ANIMCHANNEL_ALL, "low");
}

void laser_coupling_open()
{
	$laser_coupling_1.playAnim(ANIMCHANNEL_ALL, "open");
}

////////////////////////////stuff from renners old storage script/////////////////////////////

void circle_door_east()
{
	$circle_north_1.time(6);
	$circle_rotate_north_1.time(6);
	$circle_south_1.time(6);
	$circle_rotate_south_1.time(6);

	$circle_up_1.time(6);
	$circle_rotate_up_1.time(6);
	$circle_down_1.time(6);
	$circle_rotate_down_1.time(6);

	$circle_north_1.move(NORTH, 64);
	$circle_rotate_north_1.rotateOnce('0 0 45');
	$circle_south_1.move(SOUTH, 64);
	$circle_rotate_south_1.rotateOnce('0 0 45');

	$circle_up_1.move(UP, 64);
	$circle_rotate_up_1.rotateOnce('0 0 45');
	$circle_down_1.move(DOWN, 64);
	$circle_rotate_down_1.rotateOnce('0 0 45');
}
void big_doors_east()
{
	$big_door_peg_5.time(1+ sys.random(.5));
	$big_door_peg_6.time(1+ sys.random(.5));
	$big_door_peg_7.time(1+ sys.random(.5));
	$big_door_peg_8.time(1+ sys.random(.5));
	$big_door_center_rt_1.time (8);
	$big_door_center_lf_1.time (8);
		
	$big_door_peg_7.move(SOUTH, 96);				
	$big_door_peg_5.move(NORTH, 96);				
	$big_door_peg_8.move(SOUTH, 96);					
	$big_door_peg_6.move(NORTH, 96);
	
	sys.wait(2);		
	
	$big_door_center_rt_1.rotateOnce ( '0 -32 0' );
	$big_door_center_lf_1.rotateOnce ( '0 32 0' );
}
void big_doors_east_close()
{
	$big_door_peg_5.time(1+ sys.random(.5));
	$big_door_peg_6.time(1+ sys.random(.5));
	$big_door_peg_7.time(1+ sys.random(.5));
	$big_door_peg_8.time(1+ sys.random(.5));
	$big_door_center_rt_1.time (8);
	$big_door_center_lf_1.time (8);
		
	$big_door_center_rt_1.rotateOnce ( '0 32 0' );
	$big_door_center_lf_1.rotateOnce ( '0 -32 0' );
	sys.waitFor($big_door_center_rt_1);

	$big_door_peg_7.move(NORTH, 96);				
	$big_door_peg_5.move(SOUTH, 96);				
	$big_door_peg_8.move(NORTH, 96);					
	$big_door_peg_6.move(SOUTH, 96);
	
	
	// clean up stuff behind the big doors.  Maybe speed up the hangar area a bit.
	$func_static_54045.hide();
	$func_static_9983.hide();
	$light_6208.remove();
	$hangerExteriorLight.remove();
	$light_8108.remove();
	$light_8107.remove();
	$light_7934.remove();
}

void guardianGrowl()
{
	while(1)
	{
		//sys.println("growl");
		sys.trigger($growlSnd);
		sys.wait( 20 + sys.random(5) );	
		sys.trigger($growlSnd);
		sys.wait( 20 + sys.random(5) );	
	}
}
void bounceBoxes()
{
	$guardianBox_1.applyImpulse($guardianBox_1,$guardianBox_1.getWorldOrigin(),'0 0 8000000');
	$guardianBox_2.applyImpulse($guardianBox_2,$guardianBox_2.getWorldOrigin(),'0 0 8000000');
	$guardianBox_3.applyImpulse($guardianBox_3,$guardianBox_3.getWorldOrigin(),'0 0 8000000');
}
void guardianPounding()
{
	while(1)
	{
		//sys.println("pounding");
		sys.trigger($poundingSnd);
		thread bounceBoxes();
		sys.wait( 10 + sys.random(5) );	
		sys.trigger($poundingSnd);
		thread bounceBoxes();
		sys.wait( 10 + sys.random(5) );	
	}
}
void bigGuy()
{
	thread guardianGrowl();
	sys.wait(5);
	thread guardianPounding();
}
void hangar_plat_down()
{
	$lower_hangar_door.time(6);
	$lower_hangar_door.accelTime(1);
	$lower_hangar_door.decelTime(1);
	
	$guardianBox_1.applyImpulse($guardianBox_1,$guardianBox_1.getWorldOrigin(),'0 0 -800000');
	$guardianBox_2.applyImpulse($guardianBox_2,$guardianBox_2.getWorldOrigin(),'0 0 -800000');
	$guardianBox_3.applyImpulse($guardianBox_3,$guardianBox_3.getWorldOrigin(),'0 0 -800000');
	$lower_hangar_door.move(DOWN, 296);
	sys.waitFor($lower_hangar_door);	
	
	// unlock door
	$func_static_13276.setShaderParm(7, 1);
	$door_typical_138.setShaderParm(7, 1);
	$door_typical_138.lock(0);
}
void postHangarTsd()
{
	// tsd's in the next room
	thread moveTsdFast($tube_tsd_30, 224);
	thread moveTsdFast($tube_tsd_31, 224);
	thread moveTsdFast($tube_tsd_32, 224);
	thread moveTsdFast($tube_tsd_33, 224);
	thread moveTsdFast($tube_tsd_34, 224);
	thread moveTsdFast($tube_tsd_35, 224);
	
	thread envTsd($tsdScream_3);	
}
void hangerCameraMove()
{
	// Camera pans back and forth.  There might be something on the camera entity to do this, but I don't know about it.
	$hangerCamMover.time(10);
	$hangerCamMover.accelTime(2);
	$hangerCamMover.decelTime(2);

	while(1)
	{
		$hangerCamMover.rotateOnce('0 -32 0');
		sys.waitFor($hangerCamMover);
		$hangerCamMover.rotateOnce('0 32 0');
		sys.waitFor($hangerCamMover);
	}
}
void hangerFlares()
{
	entity flareEnt;
	float id = 1;

	while (1)
	{
		flareEnt = sys.getEntity( "hangerFlare_" + id );

		if ( isValidEntity( flareEnt ))
		{
			flareEnt.show();
			sys.wait(.05);
			flareEnt.hide();
		}
		id = id + 1;
		if ( id > 10 )
		{
			id = 1;
		}
	}
}

void hangerGlow()
{
	entity glowEnt;
	float id = 1;

	while (1)
	{
		glowEnt = sys.getEntity( "glow_" + id );

		if ( isValidEntity( glowEnt ))
		{
			glowEnt.show();
			sys.wait(.025);
			glowEnt.hide();
		}
		id = id + 1;
		if ( id > 20 )
		{
			id = 1;
		}
	}
}

void hangar_doors()
{
	float a;
	float b;
	
	sys.trigger($doors_open_up);
	
	thread postHangarTsd();
	
	thread hangerCameraMove();
	
	// tracer flares in the hanger	
	thread hangerFlares();	
	thread hangerGlow();	
		
	//sys.println("Open big doors");
	a = thread big_doors_east();
	sys.wait(6);
	b = thread hangar_plat_down();
	
	// once the threads are done executing...
	sys.waitForThread(a);
	sys.waitForThread(b);
	
	// hide the broken gui, show the working gui.	
	$func_static_54052.hide();
	$func_static_54047.show();
	
	$guardianBox_1.unbind();
	$guardianBox_2.unbind();
	$guardianBox_3.unbind();
}

void hangar_iris_cam()
{
	float c;

	c = thread circle_door_east();

	// once the threads are done executing...
	sys.waitForThread(c);

	// ..we have completed the requested objective
	sys.trigger($objectiveComplete_FirstTime);
}

/*--------------------------------------
START - call functions played on the func_spawner $spawnHangerMarines	
------------------------------------*/
void offShipMarines(entity shipMarines)
{
	//sys.println("run and flee");
	shipMarines.becomeAggressive();
	aiScriptedMoveWait( shipMarines, $offShipStop, 16, 1 );
	//sys.wait(5);
	sys.waitFrame();
	shipMarines.remove();
}
void shipLeaves()
{
	//sys.println("Fly away");
/*	
	// close door
	$door_typical_72.setKey("wait", 1);	
	$func_static_9983.setShaderParm(7, 1);
	$door_typical_72.setShaderParm(7, 1);
	$door_typical_72.lock(1);

	// turn off kill brush
	sys.wait(10);
	sys.trigger($killShipMarines);
*/
}
/*--------------------------------------
END - call functions played on the func_spawner $spawnHangerMarines	
------------------------------------*/
void moveRightLight()
{
	sys.trigger($rightLightFx);
	sys.trigger($dropLightRight);

	$spotRight.time(1.5);
	$spotRight.accelTime(1);
	$spotRight.decelTime(1);

	$spotRight.rotateOnce('-45 0 0');
	sys.waitFor($spotRight);

	while(1)
	{
		$spotRight.rotateOnce('10 0 0');
		sys.waitFor($spotRight);
		$spotRight.rotateOnce('0 -65 0');
		sys.waitFor($spotRight);
		$spotRight.rotateOnce('-10 0 0');
		sys.waitFor($spotRight);	
		$spotRight.rotateOnce('0 65 0');
		sys.waitFor($spotRight);
		$spotRight.rotateOnce('0 -32 0');
		sys.waitFor($spotRight);
		$spotRight.rotateOnce('0 32 0');
		sys.waitFor($spotRight);	
	}
}

void moveLeftLight()
{
	sys.trigger($leftLightFx);
	sys.trigger($dropLightLeft);

	$spotLeft.time(2);
	$spotLeft.accelTime(1);
	$spotLeft.decelTime(1);

	$spotLeft.rotateOnce('-45 0 0');
	sys.waitFor($spotLeft);

	while(1)
	{
		$spotLeft.rotateOnce('0 45 0');
		sys.waitFor($spotLeft);
		$spotLeft.rotateOnce('10 0 0');
		sys.waitFor($spotLeft);
		$spotLeft.rotateOnce('0 -45 0');
		sys.waitFor($spotLeft);
		$spotLeft.rotateOnce('-10 0 0');
		sys.waitFor($spotLeft);
	}
}

void firstMarine()
{
	aiScriptedMoveWait( $scanMarine, $firstMarineStop, 16, 1 );
	aiScriptedFaceWait ( $scanMarine, $light_7981, false );	
	
	while(1)
	{
		aiScriptedAnimWait($scanMarine, "aim_snappy_1", 4, 1);	
		aiScriptedAnimWait($scanMarine, "idle_scan_2", 4, 1);
		aiScriptedAnimWait($scanMarine, "aim_snappy_2", 4, 1);	
	}
}
void shipLanding()
{
	$func_static_53996.bindToJoint($dropShip, "base_rot", 0);
	$spotRight.bindToJoint($dropShip, "base_rot", 0);	
	$spotLeft.bindToJoint($dropShip, "base_rot", 0);	
				
	playAnimWait($dropShip, ANIMCHANNEL_ALL, "idle");

	thread moveRightLight();
	thread moveLeftLight();
	$dropShip.show();
	$func_static_53996.show();
	playAnimWait($dropShip, ANIMCHANNEL_ALL, "hangar_land");
	$dropShip.playCycle(ANIMCHANNEL_ALL, "hangar_idle");
	sys.trigger($scanMarine);
/*
	sys.wait(1);
	sys.trigger($spawnHangerMarines);
	sys.wait(1);
	$door_typical_72.setKey("wait", -1);	
	$door_typical_72.open();
*/
}

void newHangerDoor()
{
	$func_elevator_37.setGuiParm( "noninteractive", "1" );
	sys.trigger($fakeCamTrig);
	$fakeCamTrig.setKey("facing", "1");

	setNewTimes( $thickTopLeft, 5 , 3 , 1 );
	setNewTimes( $thickTopRight, 5 , 3 , 1 );
	setNewTimes( $thickBottomLeft, 5 , 3 , 1 );
	setNewTimes( $thickBottomRight, 5 , 3 , 1 );

	setNewTimes( $thinLeftDoor, 5 , 2.5 , 0 );
	setNewTimes( $thinRightDoor, 5 , 2.5 , 0 );
	setNewTimes( $thinLeftDoor_1, 5 , 2.5 , 0 );
	setNewTimes( $thinRightDoor_1, 5 , 2.5 , 0 );

	// turn on the light from outside.
	sys.trigger($hangerExteriorLight);

	$thickTopLeft.moveTo($innerTopLeft);
	$thickTopRight.moveTo($innerTopRight);
	$thickBottomRight.moveTo($innerBottomRight);
	$thickBottomLeft.moveTo($innerBottomLeft);
	sys.wait(.5);
	$thinLeftDoor.move( SOUTH, 600 );	
	$thinRightDoor.move( NORTH, 600 );	
	$thinLeftDoor_1.move( SOUTH, 600 );	
	$thinRightDoor_1.move( NORTH, 600 );	

	sys.trigger($fadein_outsideLight);

	// Opening hangar doors complete
	sys.trigger($item_objectivecomplete_2);
	// Falcon1 landing radio
	sys.trigger($func_radiochatter_21);

	sys.trigger($attackedTrig);
	//sys.trigger($trigger_once_79);

	sys.wait(2.5);
	thread shipLanding();
	sys.wait(1);
	$func_elevator_37.setGuiParm( "noninteractive", "0" );
}

//-----------------------------------------------------
// new bridge movement
//
// mrenner
//-----------------------------------------------------

void gui_in()
{
	$gui_arm.time(.25);
	$bridge_gui.time(.25);
	//$bridge_gui_1.time(.25);
	
	$gui_arm.move(EAST, 80);
	sys.trigger($gui_panel_in);
	sys.waitFor($gui_arm);
	sys.trigger($gui_panel_rotate);
	$bridge_gui.rotateOnce('0 90 0');
	//$bridge_gui_1.rotateOnce('0 90 0');	
	sys.wait(.25);
	sys.trigger($gui_panel_in);
	$gui_arm.move(EAST, 16);
	sys.waitFor($gui_arm);
}

void gui_out()
{
	$gui_arm.time(.25);
	$bridge_gui.time(.25);
	//$bridge_gui_1.time(.25);	
	
	$gui_arm.move(WEST, 16);
	sys.trigger($gui_panel_out);
	sys.waitFor($gui_arm);
	sys.trigger($gui_panel_rotate);
	$bridge_gui.rotateOnce('0 -90 0');
	//$bridge_gui_1.rotateOnce('0 -90 0');	
	sys.wait(.25);
	sys.trigger($gui_panel_out);
	$gui_arm.move(WEST, 80);
	sys.waitFor($gui_arm);
}


void bridge_setup()
{
//-----------------------------------------------------
//	North Catwalk Start
//-----------------------------------------------------
	$bridge_north_supports.time(.1);
	
	$bridge_arm_lf_a.time(.1);
	$bridge_arm_lf_b.time(.1);
	$bridge_arm_lf_c.time(.1);
	$bridge_plat_lf_a.time(.1);
	$bridge_plat_lf_b.time(.1);
	$bridge_plat_lf_c.time(.1);
	
	$bridge_arm_rt_a.time(.1);
	$bridge_arm_rt_b.time(.1);
	$bridge_arm_rt_c.time(.1);
	$bridge_plat_rt_a.time(.1);
	$bridge_plat_rt_b.time(.1);
	$bridge_plat_rt_c.time(.1);

	$bridge_north_supports.move(NORTH, 400);

	$bridge_arm_lf_a.rotateOnce('112 0 0');
	$bridge_arm_lf_b.rotateOnce('112 0 0');
	$bridge_arm_lf_c.rotateOnce('112 0 0');
	
	$bridge_plat_lf_a.rotateOnce('0 0 -22');
	$bridge_plat_lf_b.rotateOnce('0 0 -22');
	$bridge_plat_lf_c.rotateOnce('0 0 -22');

	$bridge_arm_rt_a.rotateOnce('112 0 0');
	$bridge_arm_rt_b.rotateOnce('112 0 0');
	$bridge_arm_rt_c.rotateOnce('112 0 0');

	$bridge_plat_rt_a.rotateOnce('0 0 22');
	$bridge_plat_rt_b.rotateOnce('0 0 22');
	$bridge_plat_rt_c.rotateOnce('0 0 22');
//-----------------------------------------------------
//	North Catwalk End
//-----------------------------------------------------
//-----------------------------------------------------
//	East Catwalk Start
//-----------------------------------------------------
	$bridge_east_supports.time(.1);
	
	$bridge_arm_lf_a_east.time(.1);
	$bridge_arm_lf_b_east.time(.1);
	$bridge_arm_lf_c_east.time(.1);
	$bridge_plat_lf_a_east.time(.1);
	$bridge_plat_lf_b_east.time(.1);
	$bridge_plat_lf_c_east.time(.1);
	
	$bridge_arm_rt_a_east.time(.1);
	$bridge_arm_rt_b_east.time(.1);
	$bridge_arm_rt_c_east.time(.1);
	$bridge_plat_rt_a_east.time(.1);
	$bridge_plat_rt_b_east.time(.1);
	$bridge_plat_rt_c_east.time(.1);

	$bridge_east_supports.move(EAST, 400);

	$bridge_arm_lf_a_east.rotateOnce('112 0 0');
	$bridge_arm_lf_b_east.rotateOnce('112 0 0');
	$bridge_arm_lf_c_east.rotateOnce('112 0 0');
	
	$bridge_plat_lf_a_east.rotateOnce('0 0 -22');
	$bridge_plat_lf_b_east.rotateOnce('0 0 -22');
	$bridge_plat_lf_c_east.rotateOnce('0 0 -22');

	$bridge_arm_rt_a_east.rotateOnce('112 0 0');
	$bridge_arm_rt_b_east.rotateOnce('112 0 0');
	$bridge_arm_rt_c_east.rotateOnce('112 0 0');

	$bridge_plat_rt_a_east.rotateOnce('0 0 22');
	$bridge_plat_rt_b_east.rotateOnce('0 0 22');
	$bridge_plat_rt_c_east.rotateOnce('0 0 22');
//-----------------------------------------------------
//	East Catwalk End
//-----------------------------------------------------
//-----------------------------------------------------
//	West Catwalk Start
//-----------------------------------------------------
	$bridge_west_supports.time(.1);
	
	$bridge_arm_lf_a_west.time(.1);
	$bridge_arm_lf_b_west.time(.1);
	$bridge_arm_lf_c_west.time(.1);
	$bridge_plat_lf_a_west.time(.1);
	$bridge_plat_lf_b_west.time(.1);
	$bridge_plat_lf_c_west.time(.1);
	
	$bridge_arm_rt_a_west.time(.1);
	$bridge_arm_rt_b_west.time(.1);
	$bridge_arm_rt_c_west.time(.1);
	$bridge_plat_rt_a_west.time(.1);
	$bridge_plat_rt_b_west.time(.1);
	$bridge_plat_rt_c_west.time(.1);

	$bridge_west_supports.move(WEST, 400);

	$bridge_arm_lf_a_west.rotateOnce('112 0 0');
	$bridge_arm_lf_b_west.rotateOnce('112 0 0');
	$bridge_arm_lf_c_west.rotateOnce('112 0 0');
	
	$bridge_plat_lf_a_west.rotateOnce('0 0 -22');
	$bridge_plat_lf_b_west.rotateOnce('0 0 -22');
	$bridge_plat_lf_c_west.rotateOnce('0 0 -22');

	$bridge_arm_rt_a_west.rotateOnce('112 0 0');
	$bridge_arm_rt_b_west.rotateOnce('112 0 0');
	$bridge_arm_rt_c_west.rotateOnce('112 0 0');

	$bridge_plat_rt_a_west.rotateOnce('0 0 22');
	$bridge_plat_rt_b_west.rotateOnce('0 0 22');
	$bridge_plat_rt_c_west.rotateOnce('0 0 22');
//-----------------------------------------------------
//	North Catwalk End
//-----------------------------------------------------
//-----------------------------------------------------
//	Center Bridge Start
//-----------------------------------------------------

	$center_arm_northeast.time(.1);
	$center_arm_northwest.time(.1);
	$center_arm_southeast.time(.1);
	$center_arm_southwest.time(.1);
	
	$center_walkway_northeast.time(.1);
	$center_walkway_northwest.time(.1);
	$center_walkway_southeast.time(.1);
	$center_walkway_southwest.time(.1);

	$center_arm_east.time(.1);
	$center_arm_west.time(.1);
	$center_arm_north.time(.1);
	$center_arm_south.time(.1);
	
	$center_walkway_east.time(.1);
	$center_walkway_west.time(.1);
	$center_walkway_north.time(.1);
	$center_walkway_south.time(.1);

	$center_arm_east.rotateOnce('-32 0 0');
	$center_arm_west.rotateOnce('-32 0 0');
	$center_arm_north.rotateOnce('-32 0 0');
	$center_arm_south.rotateOnce('-32 0 0');
	
	$center_walkway_east.rotateOnce('-75 0 0');
	$center_walkway_west.rotateOnce('-75 0 0');
	$center_walkway_north.rotateOnce('-75 0 0');
	$center_walkway_south.rotateOnce('-75 0 0');

	$center_arm_northeast.rotateOnce('-25 0 0');
	$center_arm_northwest.rotateOnce('-25 0 0');
	$center_arm_southeast.rotateOnce('-25 0 0');
	$center_arm_southwest.rotateOnce('-25 0 0');
	
	$center_walkway_northeast.rotateOnce('-60 0 0');
	$center_walkway_northwest.rotateOnce('-60 0 0');
	$center_walkway_southeast.rotateOnce('-60 0 0');
	$center_walkway_southwest.rotateOnce('-60 0 0');

	sys.waitFor($center_walkway_southwest);

	$center_arm_northeast.bind($center_45_arms);
	$center_arm_northwest.bind($center_45_arms);
	$center_arm_southeast.bind($center_45_arms);
	$center_arm_southwest.bind($center_45_arms);
	
	$center_45_arms.time(.1);
	$center_45_arms.move(UP, 128);
	$center_45_arms.rotateOnce('0 -45 0');
	sys.waitFor($center_45_arms);

	$center_arm_northeast.unbind();
	$center_arm_northwest.unbind();
	$center_arm_southeast.unbind();
	$center_arm_southwest.unbind();
//-----------------------------------------------------
//	Center Bridge End
//-----------------------------------------------------
}

void bridge_extend()
{
	$bridge_north_supports.accelTime(1);
	$bridge_north_supports.decelTime(1);
	$bridge_north_supports.time(3);
	$bridge_west_supports.accelTime(1);
	$bridge_west_supports.decelTime(1);
	$bridge_west_supports.time(3);
	$bridge_east_supports.accelTime(1);
	$bridge_east_supports.decelTime(1);
	$bridge_east_supports.time(3);

	$bridge_north_supports.move(SOUTH, 400);
	$bridge_west_supports.move(EAST, 400);
	$bridge_east_supports.move(WEST, 400);
	sys.waitFor($bridge_north_supports);
}

void catwalk_a()
{
	$bridge_arm_lf_a.time(2);
	$bridge_arm_rt_a.time(2);
	$bridge_plat_rt_a.time(2);
	$bridge_plat_lf_a.time(2);

	$bridge_arm_lf_a.rotateOnce('248 0 0');
	$bridge_arm_rt_a.rotateOnce('248 0 0');
	$bridge_plat_lf_a.rotateOnce('0 0 -136');
	$bridge_plat_rt_a.rotateOnce('0 0 136');
	
	sys.waitFor($bridge_arm_lf_a);
	
	$bridge_plat_rt_a.time(.5);
	$bridge_plat_lf_a.time(.5);
	
	$bridge_plat_lf_a.rotateOnce('0 0 158');
	$bridge_plat_rt_a.rotateOnce('0 0 -158');
}

void catwalk_b()
{
	$bridge_arm_lf_b.time(2);
	$bridge_arm_rt_b.time(2);
	$bridge_plat_rt_b.time(2);
	$bridge_plat_lf_b.time(2);

	$bridge_arm_lf_b.rotateOnce('248 0 0');
	$bridge_arm_rt_b.rotateOnce('248 0 0');
	$bridge_plat_lf_b.rotateOnce('0 0 -136');
	$bridge_plat_rt_b.rotateOnce('0 0 136');
	
	sys.waitFor($bridge_arm_lf_b);
	
	$bridge_plat_rt_b.time(.5);
	$bridge_plat_lf_b.time(.5);
	
	$bridge_plat_lf_b.rotateOnce('0 0 158');
	$bridge_plat_rt_b.rotateOnce('0 0 -158');
}

void catwalk_c()
{
	$bridge_arm_lf_c.time(2);
	$bridge_arm_rt_c.time(2);
	$bridge_plat_rt_c.time(2);
	$bridge_plat_lf_c.time(2);

	$bridge_arm_lf_c.rotateOnce('248 0 0');
	$bridge_arm_rt_c.rotateOnce('248 0 0');
	$bridge_plat_lf_c.rotateOnce('0 0 -136');
	$bridge_plat_rt_c.rotateOnce('0 0 136');
	
	sys.waitFor($bridge_arm_lf_c);
	
	$bridge_plat_rt_c.time(.5);
	$bridge_plat_lf_c.time(.5);
	
	$bridge_plat_lf_c.rotateOnce('0 0 158');
	$bridge_plat_rt_c.rotateOnce('0 0 -158');
}

void catwalk_a_east()
{
	$bridge_arm_lf_a_east.time(2);
	$bridge_arm_rt_a_east.time(2);
	$bridge_plat_rt_a_east.time(2);
	$bridge_plat_lf_a_east.time(2);

	$bridge_arm_lf_a_east.rotateOnce('248 0 0');
	$bridge_arm_rt_a_east.rotateOnce('248 0 0');
	$bridge_plat_lf_a_east.rotateOnce('0 0 -136');
	$bridge_plat_rt_a_east.rotateOnce('0 0 136');
	
	sys.waitFor($bridge_arm_lf_a_east);
	
	$bridge_plat_rt_a_east.time(.5);
	$bridge_plat_lf_a_east.time(.5);
	
	$bridge_plat_lf_a_east.rotateOnce('0 0 158');
	$bridge_plat_rt_a_east.rotateOnce('0 0 -158');
}

void catwalk_b_east()
{
	$bridge_arm_lf_b_east.time(2);
	$bridge_arm_rt_b_east.time(2);
	$bridge_plat_rt_b_east.time(2);
	$bridge_plat_lf_b_east.time(2);

	$bridge_arm_lf_b_east.rotateOnce('248 0 0');
	$bridge_arm_rt_b_east.rotateOnce('248 0 0');
	$bridge_plat_lf_b_east.rotateOnce('0 0 -136');
	$bridge_plat_rt_b_east.rotateOnce('0 0 136');
	
	sys.waitFor($bridge_arm_lf_b_east);
	
	$bridge_plat_rt_b_east.time(.5);
	$bridge_plat_lf_b_east.time(.5);
	
	$bridge_plat_lf_b_east.rotateOnce('0 0 158');
	$bridge_plat_rt_b_east.rotateOnce('0 0 -158');
}

void catwalk_c_east()
{
	$bridge_arm_lf_c_east.time(2);
	$bridge_arm_rt_c_east.time(2);
	$bridge_plat_rt_c_east.time(2);
	$bridge_plat_lf_c_east.time(2);

	$bridge_arm_lf_c_east.rotateOnce('248 0 0');
	$bridge_arm_rt_c_east.rotateOnce('248 0 0');
	$bridge_plat_lf_c_east.rotateOnce('0 0 -136');
	$bridge_plat_rt_c_east.rotateOnce('0 0 136');
	
	sys.waitFor($bridge_arm_lf_c_east);
	
	$bridge_plat_rt_c_east.time(.5);
	$bridge_plat_lf_c_east.time(.5);
	
	$bridge_plat_lf_c_east.rotateOnce('0 0 158');
	$bridge_plat_rt_c_east.rotateOnce('0 0 -158');
}

void catwalk_a_west()
{
	$bridge_arm_lf_a_west.time(2);
	$bridge_arm_rt_a_west.time(2);
	$bridge_plat_rt_a_west.time(2);
	$bridge_plat_lf_a_west.time(2);

	$bridge_arm_lf_a_west.rotateOnce('248 0 0');
	$bridge_arm_rt_a_west.rotateOnce('248 0 0');
	$bridge_plat_lf_a_west.rotateOnce('0 0 -136');
	$bridge_plat_rt_a_west.rotateOnce('0 0 136');
	
	sys.waitFor($bridge_arm_lf_a_west);
	
	$bridge_plat_rt_a_west.time(.5);
	$bridge_plat_lf_a_west.time(.5);
	
	$bridge_plat_lf_a_west.rotateOnce('0 0 158');
	$bridge_plat_rt_a_west.rotateOnce('0 0 -158');
}

void catwalk_b_west()
{
	$bridge_arm_lf_b_west.time(2);
	$bridge_arm_rt_b_west.time(2);
	$bridge_plat_rt_b_west.time(2);
	$bridge_plat_lf_b_west.time(2);

	$bridge_arm_lf_b_west.rotateOnce('248 0 0');
	$bridge_arm_rt_b_west.rotateOnce('248 0 0');
	$bridge_plat_lf_b_west.rotateOnce('0 0 -136');
	$bridge_plat_rt_b_west.rotateOnce('0 0 136');
	
	sys.waitFor($bridge_arm_lf_b_west);
	
	$bridge_plat_rt_b_west.time(.5);
	$bridge_plat_lf_b_west.time(.5);
	
	$bridge_plat_lf_b_west.rotateOnce('0 0 158');
	$bridge_plat_rt_b_west.rotateOnce('0 0 -158');
}

void catwalk_c_west()
{
	$bridge_arm_lf_c_west.time(2);
	$bridge_arm_rt_c_west.time(2);
	$bridge_plat_rt_c_west.time(2);
	$bridge_plat_lf_c_west.time(2);

	$bridge_arm_lf_c_west.rotateOnce('248 0 0');
	$bridge_arm_rt_c_west.rotateOnce('248 0 0');
	$bridge_plat_lf_c_west.rotateOnce('0 0 -136');
	$bridge_plat_rt_c_west.rotateOnce('0 0 136');
	
	sys.waitFor($bridge_arm_lf_c_west);
	
	$bridge_plat_rt_c_west.time(.5);
	$bridge_plat_lf_c_west.time(.5);
	
	$bridge_plat_lf_c_west.rotateOnce('0 0 158');
	$bridge_plat_rt_c_west.rotateOnce('0 0 -158');
}

void bridge_unfold()
{
	$gui_out.remove();
	$gui_in.remove();

	float	lowerTime = 3;

	$center_arm_northeast.time(lowerTime );
	$center_arm_northwest.time(lowerTime );
	$center_arm_southeast.time(lowerTime );
	$center_arm_southwest.time(lowerTime );
	
	$center_walkway_northeast.time(lowerTime);
	$center_walkway_northwest.time(lowerTime);
	$center_walkway_southeast.time(lowerTime);
	$center_walkway_southwest.time(lowerTime);

	$center_arm_east.time(lowerTime);
	$center_arm_west.time(lowerTime);
	$center_arm_north.time(lowerTime);
	$center_arm_south.time(lowerTime);
	
	$center_walkway_east.time(lowerTime);
	$center_walkway_west.time(lowerTime);
	$center_walkway_north.time(lowerTime);
	$center_walkway_south.time(lowerTime);

	$center_arm_east.bind($center_45_arms);
	$center_arm_west.bind($center_45_arms);
	$center_arm_north.bind($center_45_arms);
	$center_arm_south.bind($center_45_arms);
	$center_arm_northeast.bind($center_45_arms );
	$center_arm_northwest.bind($center_45_arms );
	$center_arm_southeast.bind($center_45_arms );
	$center_arm_southwest.bind($center_45_arms );
	
	$center_45_arms.time(3);	
	$center_45_arms.rotateOnce('0 180 0');

	$center_arm_east.rotateOnce('32 0 0');
	$center_arm_west.rotateOnce('32 0 0');
	$center_arm_north.rotateOnce('32 0 0');
	$center_arm_south.rotateOnce('32 0 0');
	
	$center_walkway_east.rotateOnce('75 0 0');
	$center_walkway_west.rotateOnce('75 0 0');
	$center_walkway_north.rotateOnce('75 0 0');
	$center_walkway_south.rotateOnce('75 0 0');

	$center_arm_northeast.rotateOnce('25 0 0');
	$center_arm_northwest.rotateOnce('25 0 0');
	$center_arm_southeast.rotateOnce('25 0 0');
	$center_arm_southwest.rotateOnce('25 0 0');
	
	$center_walkway_northeast.rotateOnce('60 0 0');
	$center_walkway_northwest.rotateOnce('60 0 0');
	$center_walkway_southeast.rotateOnce('60 0 0');
	$center_walkway_southwest.rotateOnce('60 0 0');
}

void catwalks()
{
	thread catwalk_c();
	sys.wait(.25);
	thread catwalk_b();
	sys.wait(.25);
	thread catwalk_a();	
	sys.wait(1);
	thread catwalk_a_east();
	thread catwalk_a_west();
	sys.wait(.25);
	thread catwalk_b_east();
	thread catwalk_b_west();
	sys.wait(.25);
	thread catwalk_c_east();
	thread catwalk_c_west();
}

void shaft_bridge()
{
	sys.wait(.5);
	thread gui_in();
	thread bridge_extend();
	
	sys.waitFrame();
	$bridge_gui.setGuiParm("noninteractive", "1"); // the gui can't be clicked until this is set back to 0
	
//	$bridge_gui.hide();
//	$bridge_gui_2.show();
			
	sys.wait(3);
		
	thread bridge_unfold();
	thread catwalks();
	
	$door_typical_70.lock(0);
}

//-----------------------------------------------------
// swaps any entity with a char marine.
//
// jshepard
//-----------------------------------------------------
void swapWithCharMarine(entity entSwap)
{
	//get the location and facing of the entity
	vector vLoc = entSwap.getWorldOrigin();
	vector vAng = entSwap.getAngles();

	//remove the entity
	entSwap.remove();
	
	//just for fun
	//sys.playWorldEffect("effects/explosions/surface/white_cloud",vLoc,'0 0 1');
	//sys.wait(.5);

	//set up a new one
	entity newEnt = sys.spawn("char_marine_new");
	newEnt.setWorldOrigin(vLoc);
	newEnt.setAngles(vAng);

	//cha cha cha
}

//-----------------------------------------------------
// Shows the pod crash-- needs fixin'
//
// jshepard
//-----------------------------------------------------
void runCrashAnim()
{
	//this function moves the player to the crash site but
	//requires him to step in the vehicle. If he doesn't step 
	//in before it takes off, too bad!

	//FIXME: Need an auto-insert function that stuffs the player in a vehicle.
	//TODO: Create an auto-insert function that stuffs the player in a vehicle.
	//TODO: Fix the crashpod so it can play animations.

	//move to crash site
	//sys.println("Tester, please enter the escape pod before the countdown expires.");
//	$player1.setWorldOrigin($tgt_crash_start.getWorldOrigin());

	sys.wait(4);
	//sys.println("Storage pod crash... 3...");
	sys.wait(1);
	//sys.println("..2..");
	
	//bind the pod to the animated bone,	
	$env_storage_pod_crash_1.bindToJoint($crash_anim, "animated", 1);

	//move the pod into launch position.
	$crash_anim.setWorldOrigin($tgt_launch.getWorldOrigin());
	sys.wait(1);
	//sys.println("..1..");
	sys.wait(1);
	
	//crashinate!
	$crash_anim.playAnim( ANIMCHANNEL_ALL, "pod_crash"); 
	//sys.println("Go!");

	// TODO: the objective should get triggered at the end of the pod drop sequence, which isn't in yet.
	sys.wait(20);
	//sys.trigger($object_FirstTime);
}

///////////////////////////////////////////////
///////////////////////////////////////////////
//
//	beamcoupler as it connects to the core.		mrenner
//
///////////////////////////////////////////////
///////////////////////////////////////////////
void beamSetup()
{
	$beam_rail_north.time(.1);
	$beam_rail_south.time(.1);
	$beam_rail_north.move( DOWN,992 );
	$beam_rail_south.move( DOWN,992 );

	$beam_satellite.time(.1);
	$beam_satellite.move( EAST,96 );
	sys.waitFor($beam_satellite);
	$beam_satellite.rotateOnce( '90 0 0' );
}

// -------------------
// This is the most evil hack ever perpetrated upon modern game design:
//
// The beam doesn't fire far enough to still appear to hit the top of the core tower,
// because the beam is locked in place but the skybox moves with the player.
//
// This loop gets the player's position and moves the target point of the beam effect
// to compensate, so that the end point is always over the apparent top of the core tower.
// mbreit | aug 05
// -------------------
void beamParallax() {
	vector pOrg;
	vector cOrg = '-1 0.0234375 0.56875';	// vector to core tower top, x-normalized
	vector nOrg;
	float a;
	while (1) {
		pOrg = $player1.getWorldOrigin() + '0 0 68';	// eye height (standing)
		a = (pOrg_x + 19700); 	// beam fx stop drawing at ~19700 x, so measure x distance
					// from player. without sky caulk this would be the exact 
					// x coordinate of the wall instead (where the beam clips off)
		nOrg = cOrg * a + pOrg;		// multiply core vector to full distance so we're at the end of the beam
		$null_beamTarget.setWorldOrigin( nOrg );	// point the emitter here
	//	sys.println("Origin set to" + nOrg_x + " " + nOrg_y + " " + nOrg_z + ".");
		sys.waitFrame();	// rinse, repeat
	}
}

void beamCoupler()
{	
	// brief warm-up
	$coupler_axis.time(1.5);
	$coupler_axis.accelTime(1.5);
	
	sys.trigger($coupling_spin_sound);
	$coupler_axis.rotateOnce( '0 0 360' );
	sys.waitFor($coupler_axis);

	// now start effect and just rotate forever (could use a func_rotate?)
	thread beamParallax();
	sys.trigger( $fx_roofCoreConnection );
	sys.trigger( $spkr_roof_core_speaker );

	$coupler_axis.time(.25);
	$coupler_axis.accelTime(0);
	
	while(1)
	{
		$coupler_axis.rotateOnce( '0 0 90' );
		sys.waitFor($coupler_axis);
	}
}

void exitElevator()
{
	// lock doors
	$func_static_12708.setShaderParm(7, 0);	
	$func_static_12707.setShaderParm(7, 0);	
	$door_typical_133.setShaderParm(7, 0);	
	$door_typical_133.lock(1);

	// show the elevator (and all it's parts) that will take the player to the level exit.
	
	sys.trigger($endLevelTrig);
	
	$exit_elevator.show();
	$exitElevatorClip.show();
	$func_static_53541.show();
	$func_static_53542.show();
	$func_static_53543.show();	

	sys.trigger($exit_elevator_light1);
	sys.trigger($exit_elevator_light2);
	
	sys.trigger($trigger_multiple_2);
	$func_mover_12241.show();
}
void goodJob()
{
	// "Well done, Kane."
	//sys.println("Well done, Kane.");
	radioChatterPlayWait ($straussGoodJob, "");
	
	// new objective to get to the elevator to the tram.
	sys.trigger($item_objective_6);
	
	aiSpeakWait( $Rhodes, "lipsync_vo_3_1_4_80_2" );
	$Rhodes.setPassivePrefix("end");				
}
void activateBeam()
{
	$laser_coupling_1.playCycle(ANIMCHANNEL_ALL, "spin_loop");

	sys.trigger($beamLightsOn);

	sys.trigger($item_objectivecomplete_4);

	thread goodJob();

	// triggers a relay that connects to a few triggers
	//sys.trigger($afterBeamRelay);

	//sys.println("Rotate Floor");
	
	// rotate the thing you're standing on
	
	$mvr_dishMachines_pivot.time(3);
	$mvr_dishMachines_pivot.rotateDownTo(1, 180);
	sys.waitFor($mvr_dishMachines_pivot);

	// now activate the beam
	
	sys.trigger($disc_sound);
	$disc_north.rotateOnce( '0 -24 0' );
	$disc_south.rotateOnce( '0 24 0' );
	sys.wait(0.5);
	
	sys.trigger($disc_sm_sound);
	$disc_north_sm.rotateOnce( '0 -45 0' );
	$disc_south_sm.rotateOnce( '0 45 0' );

	$beam_rail_north.show();
	$beam_rail_south.show();

	$func_static_54026.show();
	$func_static_54024.show();
	$func_static_54023.show();
	$func_static_54025.show();

	$beam_satellite.show();
	$beam_coupler.show();
		
	$beam_rail_north.time(3);
	$beam_rail_south.time(3);
	
	$beam_satellite.time(3);
	sys.waitFor($disc_south_sm);
	
	sys.trigger($rail_sound);

	$beam_rail_north.move( UP,992 );
	$beam_rail_south.move( UP,992 );
	sys.waitFor($beam_rail_south);
	
	sys.trigger($coupling_rise_sound);
	$beam_satellite.move( UP,464 );	
	sys.waitFor($beam_satellite);
	sys.wait(1);
	sys.trigger($coupling_aim_sound);
	$beam_satellite.move( DOWN,64 );
	$beam_satellite.rotateOnce( '-119.1 0 0' );	// point at the top of this tower
	sys.waitFor($beam_satellite);

	thread beamCoupler();
	thread exitElevator();
	
	// activate the elevators.	
	sys.trigger($trigger_relay_33);
	
	// activate triggs for on the way back through transfer area.
	//	sys.trigger($rhodesPostRoofTrig);

	// set Rhodes back to the elevator.
	//	sys.trigger($ai_tether_radius_15);
	//	sys.wait(2);
	//	thread goodJob();
}

//-------------------------------------------------------------------------------------------
// drop ship
//-------------------------------------------------------------------------------------------
void buzzPlayer()	{

	while( $daredevil_sound.distanceTo( $player1 ) > 2048 )	{
		
		//sys.println("Wait for it...");
		sys.wait( .5 );
		
	}
	
	sys.trigger( $daredevil_sound );
	//sys.println( "PLAYING!" );
	
}
void dropOff()	
{
	$daredevilDropship.show();
	
	// was asked to make the dropoff happen faster...this will make it easier to adjust the whole sequence and keep
	//	all of the times listed below correct
	//float rate = 0.6666; (changing times/fixing stuff anyway; will address with static times -aweldon)

	setNewTimes( $daredevil_base , 3 , 0 , 1 );
	$daredevil_base.startSpline( $func_splinemover_1 );
	
	thread buzzPlayer();

	//sys.wait(2);
	
	setNewTimes( $daredevil_axis , 2 , 1 , 1 );
	$daredevil_axis.rotateOnce( '0 0 45' );
	sys.waitFor( $daredevil_axis );

	setNewTimes( $daredevil_axis , 1 , .5 , .5 );
	$daredevil_axis.rotateOnce( '0 0 -45' );
	sys.waitFor( $daredevil_axis );

	sys.waitFor( $daredevil_base );
	
	strogg_dropship::carrierLand( $daredevilDropship );
	
	setNewTimes( $daredevil_base , 8 , 2 , 0 );
	$daredevil_base.startSpline( $func_splinemover_2 );
//	thread buzzPlayer();
	sys.trigger( $daredevil_sound );
	
	//ROTATIONS
	
	setNewTimes( $daredevil_axis , 1 , .5 , .5 );
	$daredevil_axis.rotateOnce( '0 0 24' );
	sys.waitFor( $daredevil_axis );

	setNewTimes( $daredevil_axis , 7 , 1 , 1 );
	$daredevil_axis.rotateOnce( '0 0 -90' );
	sys.waitFor( $daredevil_axis );
	
	sys.waitFor( $daredevil_base );
	$daredevil_base.remove();

	//$daredevilDropship.hide();
}


void bentHallwayShow()
{
	$bentHallway.show();
	$func_static_13038.show();
	$func_static_13041.show();
	//sys.trigger($light_7332);

	sys.trigger($light_8116);
	$light_8116.hide();
	$func_static_54005.hide();
	$func_static_54007.hide();
	$func_static_54006.hide();
	$func_static_54008.hide();

	// rolly TSD on the ground
	$func_static_54014.show();
	sys.trigger($screaming_tsd_1);
	sys.trigger($speaker_7);
}
void swapBentPods()
{
	$bentPod.hide();
	$func_static_13195.show();
	sys.trigger($bentPodSnd);
}

void bentPodCrash()
{
	thread bentHallwayShow();
	
	$bentPod.time(.6);
	$bentPod.show();
	$bentPod.moveTo($target_null_76);
	sys.trigger($big_boom_6);
	sys.wait(.3);
	sys.trigger($big_boom_5);
	sys.wait(.2);
	sys.trigger($big_boom_4);
	sys.wait(.1);
	thread swapBentPods();
	sys.trigger($func_fx_131);

	sys.trigger($light_8118);
	$light_8118.hide();
	$func_static_54011.hide();
	$func_static_54010.show();
	sys.trigger($light_8117);
	
	sys.wait(.1);	
	$func_static_54009.hide();
	$func_static_54012.hide();
	sys.trigger($light_8119);
	
	$func_static_13203.show();
	$func_static_13191.show();
	$func_static_13204.show();
	$func_static_13206.show();
	
	$func_static_13209.show();
	$func_static_13207.show();
	
	sys.trigger($func_fx_9);
	sys.trigger($light_7334);
	sys.trigger($light_7333);
	sys.trigger($light_6213);
	
	//sys.wait(3);
	// "My pod. It's on fire."
	//radioChatterPlayWait ($func_radiochatter_6, "");
}

void bentHallwaySetup()
{
	$bentHallway.hide();
	$func_static_13038.hide();
	$func_static_13041.hide();
}
void postCrash()
{
	//unrelated TSD animation...
	$screaming_tsd_1.playCycle(ANIMCHANNEL_ALL, "roller");
}
void floorTsd()
{
	sys.trigger($speaker_7);
	$screaming_tsd_1.show();
	$screaming_tsd_1.playCycle(ANIMCHANNEL_ALL, "roller");
}
void pathSecond()
{
	// the players path when the level is visited for a second time.
	
	// lock doors
	$func_static_9432.setShaderParm(7, 0);	
//	$func_static_9433.setShaderParm(7, 0);	
	$door_typical_54.setShaderParm(7, 0);	
	$door_typical_54.lock(1);
	
//	$func_static_9496.setShaderParm(7, 0);	
	$func_static_9495.setShaderParm(7, 0);	
	$door_typical_57.setShaderParm(7, 0);	
	$door_typical_57.lock(1);
	
//	$func_static_8347.setShaderParm(7, 0);	
	$func_static_8346.setShaderParm(7, 0);	
	$door_typical_53.setShaderParm(7, 0);	
	$door_typical_53.lock(1);

	$func_static_11583.setShaderParm(7, 0);	
	$door_typical_97.setShaderParm(7, 0);	
	$door_typical_97.lock(1);


	// unlock doors
	$func_static_10266.setShaderParm(7, 1);
	$door_typical_74.setShaderParm(7, 1);	
	$door_typical_74.lock(0);
	$func_static_9498.setShaderParm(7, 1);	
	$door_typical_58.setShaderParm(7, 1);	
	$door_typical_58.lock(0);	
	
	// open fire doors
	openFireDoor($fire_door_lf_07, $fire_door_rt_07, $tgt_hinge_7);
	openFireDoor($fire_door_lf_08, $fire_door_rt_08, $tgt_hinge_8);	

	// put out the fire fx
	sys.trigger($func_fx_71);
	sys.trigger($func_fx_61);

	// spawn repair bots
//	sys.trigger($monster_repair_bot_1);
//	sys.trigger($monster_repair_bot_2);  //This is the one that blocks the progression?
	
	//unrelated TSD animation...
	sys.trigger($speaker_7);
}

void pilotReminder()
{
	while(1)
	{
		// "awaiting activation of the hangar"
		radioChatterPlayWait ($func_radiochatter_17, "");
		sys.wait( 30 + sys.random(10) );	
		
		// "burning up fuel here."
		radioChatterPlayWait ($func_radiochatter_18, "");
		sys.wait( 30 + sys.random(10) );	
			
		// "this zone is hot and I need to land"
		radioChatterPlayWait ($func_radiochatter_19, "");
		sys.wait( 30 + sys.random(10) );	
	}
}
void introTsds()
{
	thread moveTsdFast($tube_tsd_22, 224);
	sys.wait(.2);
	thread 	moveTsdFast($tube_tsd_23, 224);
	sys.wait(.5);
	thread moveTsdFast($tube_tsd_24, 224);
}
void moveHollenbeck2()
{
	sys.wait(3);
	aiScriptedAnimWait($Hollenbeck2, "point_left", 4, 1);
}
void meetHollenbeck2()
{
	$Hollenbeck2.lookAt($player1);
	thread moveHollenbeck2();
	$Hollenbeck2.setTalkState ( TALK_OK ); 
	aiSpeakWait( $Hollenbeck2, "lipsync_1" );
	
	// Objective to open the hangar doors
	sys.trigger($item_objective_3);
	
	sys.wait( 10 + sys.random(5) );	
	thread pilotReminder();

	// set up for the dropship flares
	sys.trigger($leftLightFx);
	sys.trigger($rightLightFx);
}
void screamingTsd()
{
	thread envTsd($tsdScream);
}
void screamingTsd2()
{
	thread envTsd($tsdScream_1);	
	thread envTsd($tsdScream_2);	
}
void hangarEntrance()
{
	thread moveTsdFast($tube_tsd_25, 224);
	sys.wait(.1);
	thread moveTsdAngle($tube_tsd_26, $target_null_60, $target_null_61 );	
	sys.wait(.2);
	thread moveTsdAngle($tube_tsd_27, $target_null_62, $target_null_63 );	
	thread moveTsdSouth($tube_tsd_28, 224);
	thread moveTsdSouth($tube_tsd_29, 224);
}

void rhodes2Radio()
{
	aiScriptedAnimWait($Rhodes, "idle_wrist_gui_start_fast", 4, 1);
	aiScriptedAnimWait($Rhodes, "idle_wrist_gui_end_fast", 4, 1);
}
void reminderRhodes()
{
	sys.threadname("mydumbthread");
	sys.wait(10);
	
	while(1)
	{
		// "get on with our mission"
		thread rhodes2Radio();
		aiSpeak( $Rhodes, "lipsync_vo_3_1_3_170_3" );				
		radioChatterPlayWait ($func_radiochatter_31, "");
		sys.wait( 20 + sys.random(20) );	

		// "Find me"
		thread rhodes2Radio();
		aiSpeak( $Rhodes, "lipsync_vo_3_1_3_170_1" );		
		radioChatterPlayWait ($func_radiochatter_29, "");
		sys.wait( 20 + sys.random(20) );	

		// "Where are you?"
		thread rhodes2Radio();
		aiSpeak( $Rhodes, "lipsync_vo_3_1_3_170_2" );		
		radioChatterPlayWait ($func_radiochatter_30, "");
		sys.wait( 20 + sys.random(20) );	
	}
}
void keiferDie()
{
	aiScriptedAnimWait( $Keifer, "ad_wounded_on_knee", 4, 1);
	aiScriptedAnimLoop( $Keifer, "ad_wounded_on_knee_dead", 1);
}
void spawnKeifer()
{
	thread keiferDie();
	
	$func_static_53989.show();
	$func_static_53990.show();
	$func_static_53988.show();
	$func_static_53987.show();	
		
	sys.wait(2);
	aiSpeakWait( $Keifer, "lipsync_1" );
	aiSpeakWait( $Keifer, "lipsync_2" );
}
void cprGuys()
{
	sys.trigger($Ramirez);
	sys.trigger($Moire);

	$Moire.setTalkState(TALK_WAIT);	

	aiScriptedAnimLoop( $Moire, "ad_cpr_1", 1);
	aiScriptedAnimLoop( $Ramirez, "ad_cpr_2", 1);

	aiSpeakWait( $Ramirez, "lipsync_1" );
	sys.wait(5);
	aiSpeakWait( $Ramirez, "lipsync_2" );
	sys.wait(5);
	aiSpeakWait( $Ramirez, "lipsync_3" );
	sys.wait( 40 + sys.random(5) );			
	
	while(1)
	{
		aiSpeakWait( $Ramirez, "lipsync_1" );
		sys.wait( 40 + sys.random(5) );			
		aiSpeakWait( $Ramirez, "lipsync_3" );
		sys.wait( 40 + sys.random(5) );				
		aiSpeakWait( $Ramirez, "lipsync_2" );
		sys.wait( 40 + sys.random(5) );			
		aiSpeakWait( $Ramirez, "lipsync_3" );
		sys.wait( 40 + sys.random(5) );				
	}
}
void spawnHart()
{
	$Hart.setTalkState( TALK_WAIT ); 	

	$Hart.hideSurface("models/weapons/mp_guns/w_sg");
	$Hart.hideSurface("models/weapons/mp_guns/w_sg_mod_ammo");
	$Hart.hideSurface("models/weapons/mp_guns/w_mg_lo");

	$Hart.showSurface("models/weapons/mp_guns/w_hb");
	$Hart.showSurface("models/weapons/mp_guns/w_hb_battery");
}
void giveBounce2()
{
	//sys.println("New mod");
	aiScriptedAnimWait($Hart, "player_gift_start", 4, 1);
	$Hart.hideSurface("models/weapons/mp_guns/w_hb");
	$Hart.hideSurface("models/weapons/mp_guns/w_hb_battery");
	sys.trigger($giveBounce_1);
	sys.trigger($pickUpWeaponSnd);
	aiScriptedAnimWait($Hart, "player_gift_end", 4, 1);
	
	//sys.println("Heal!");	
	$Hart.setTalkState( TALK_OK ); 	
	$Hart.enableHeal();
	aiScriptedAnimLoop($Hart, "unarmed_idle",1);
}
void weaponMod()
{
	$Hart.lookAt($player1);
	thread giveBounce2();
	aiSpeakWait( $Hart, "lipsync_2" );
//	aiScriptedAnimWait( $Hart, "ad_sgt_holding_wounded", 4, 0 );
}
void schwartzOrders()
{
	$Schwartz.lookAt($Glovels);
	aiSpeakWait( $Schwartz, "lipsync_1" );
	// tether Glovels
	sys.trigger($ai_tether_radius_31);
	$Schwartz.lookAt($Hart);
	aiSpeakWait( $Schwartz, "lipsync_2" );
	$Schwartz.lookAt($player1);
	// activate the trigger around schwartz.
	sys.trigger($meetSchwartzTrig);

	aiSpeak( $Glovels, "lipsync_1" );
	sys.wait(.25);
	aiSpeak( $Hart, "lipsync_1" );
}
void meetSchwartz()
{
	aiSpeakWait( $Schwartz, "lipsync_3" );
	$Schwartz.lookAt($null_entity);
}
void dullPain()
{
	aiSpeakWait( $Border, "lipsync_1" );
	aiSpeakWait( $Holmes, "lipsync_1" );
}
void hurtsGuys()
{
	sys.trigger($Border);
	sys.trigger($Holmes);	
	aiScriptedAnimLoop( $Border, "explosion_assist_loop", 1);
	aiScriptedAnimLoop( $Holmes, "explosion_injured_loop", 1);
	
	$func_static_53993.show();
	$func_static_53994.show();
	$func_static_53992.show();
	$func_static_53995.show();

}
void injured()
{
	thread cprGuys();
//	thread hurtsGuys();
}

void initNetworkGuardian()	// 3/25/05 gc
{
	$fx_guardian_jet_pack_left.bindToJoint($guardian, "l_jet", 1);
	$fx_guardian_jet_pack_right.bindToJoint($guardian, "r_jet", 1);
}
void guardianJetsOff()	// 3/25/05 gc
{
	$fx_guardian_jet_pack_left.stop();
	$fx_guardian_jet_pack_right.stop();
}
void guardianJetsOn()	// 3/25/05 gc
{
	$fx_guardian_jet_pack_left.start();
	$fx_guardian_jet_pack_right.start();
}
void cleanUpHangar()
{
	$dropShip.hide();
	sys.trigger($dropLightRight);
	sys.trigger($dropLightLeft);
	$rightLightFx.remove();
	$leftLightFx.remove();
	$func_static_53996.hide();
}

void swapCatwalk()
{
	$brokenCatwalk.show();
	$brokenGui_1.show();
	$brokenGui_2.show();
	$brokenGui_3.show();
	$brokenGui_4.show();
	
	$catwalk_good.hide();
	$railing_good.hide();
	$railing_good_clip.hide();
	$func_static_13274.hide();
	$func_static_13272.hide();
	$func_static_13273.hide();
	$func_static_13275.hide();

	sys.trigger($catwalkSwapHurt);

	sys.trigger($func_fx_561);
	$catwalk_fireClip.show();
	sys.trigger($catwalkFireTrig);
	
	sys.wait(.2);
	$catwalkSwapHurt.remove();
}

void tossMarines()
{
	//entity marine;

	// Spawn ragdoll marine and throw
	//sys.setSpawnArg( "classname", "char_marine" );
	//sys.setSpawnArg( "def_head", "char_marinehead_half" );
	//sys.setSpawnArg( "origin", $deadMarineSpot.getWorldOrigin());
	//marine = sys.spawn( "char_marine" );
	//marine.kill();

	//sys.waitFrame();
	//marine.applyImpulse( marine, marine.getWorldOrigin(),'-50000 -25000 80000');	
}
void tossMarines2()
{
	//entity marine;

	// Spawn ragdoll marine and throw
	//sys.setSpawnArg( "classname", "char_marine" );
	//sys.setSpawnArg( "def_head", "char_marinehead_helmet" );
	//sys.setSpawnArg( "origin", $deadMarineSpot_1.getWorldOrigin());
	//marine = sys.spawn( "char_marine" );
	//marine.kill();

	//sys.waitFrame();
	//marine.applyImpulse( marine, marine.getWorldOrigin(),'50000 -30000 80000');	
}
void floorClip()
{
	sys.wait(1.75);
	sys.trigger($breakOutTear);
	sys.trigger($breakOutMusic);
	sys.wait(.25);
	$bustedFloorClip.show();
	$guardian_clip.remove();
	$func_mover_12240.remove();
}
void breakingFloor()
{
	// kill the rhodes reminder loop
	//sys.println("kill the rhodes reminder loop");
	sys.killthread( "map_storage1::allSecondRadio");
	sys.killthread( "mydumbthread");
	sys.killthread( "map_storage1::rhodes2Radio");
	
	//sys.println("working?");
	
	$func_static_9499.setShaderParm(7, 0);
	$door_typical_59.setShaderParm(7, 0);	
	$door_typical_59.lock(1);

	thread cleanUpHangar();
	
	$guardianBox_1.remove();
	$guardianBox_2.remove();
	$guardianBox_3.remove();

	// kill the pounding sound loop
	sys.killthread( "map_storage1::guardianPounding");

	// kill the pounding sound loop
	sys.killthread( "map_storage1::guardianGrowl");

	$door_typical_138.open();
	
	$func_mover_11977.hide();
	// guardian lighting on
	sys.trigger($underGuardianLight);

	$guardianFloor.show();
	$guardian_clip.show();
	sys.trigger($guardian);
	$guardianFloor.playAnim(ANIMCHANNEL_ALL, "busted");
	thread floorClip();	
	aiScriptedAnimWait($guardian, "break_floor", 4, 1);
	$guardian.remove();
}
void meetRhodes()
{
	$Rhodes.setTalkState ( TALK_WAIT ); 	

	$func_static_9941.setShaderParm(7, 1);
	$door_typical_71.setShaderParm(7, 1);	
	$door_typical_71.lock(0);
	$door_typical_71.open();

	sys.wait(1);

	// set Rhodes to passive and move him into the room.
	sys.trigger($rhodesPassive);
	sys.trigger($ai_tether_radius_33);

	//  Meet Rhodes objective, complete.
	sys.trigger($item_objectivecomplete_3);
	
	$Rhodes.lookAt($player1);

	aiSpeak( $Rhodes, "lipsync_vo_3_1_3_180_1" );
	sys.wait(4);
	aiScriptedAnimWait($Rhodes, "idle_wrist_gui_start_fast", 4, 1);
	aiScriptedAnimLoop( $Rhodes, "idle_wrist_gui_loop", 1);
	aiSpeakDone( $Rhodes );	

	//sys.println("setLeader for Rhodes, temp for right now.");
	$Rhodes.setLeader($player1);

	aiScriptedAnimWait($Rhodes, "idle_wrist_gui_end_fast", 4, 1);
	// Strauss over the radio
	radioChatterPlayWait ($func_radiochatter_32, "");	
	
	// Security Station Objective.
	sys.trigger($item_objective_5);
	sys.wait(1);
	
	aiScriptedAnimWait($Rhodes, "idle_wrist_gui_start_fast", 4, 1);
	aiSpeak( $Rhodes, "lipsync_vo_3_1_3_180_3" );
	aiSpeakDone( $Rhodes );	
	$Rhodes.setTalkState ( TALK_OK ); 	
	aiScriptedAnimWait($Rhodes, "idle_wrist_gui_end_fast", 4, 1);
	
	// unlock the door on the other side the main elevator shaft.
	$func_static_9545.setShaderParm(7, 1);
	$func_static_9546.setShaderParm(7, 1);	
	$door_typical_62.setShaderParm(7, 1);	
	$door_typical_62.lock(0);
	
	// turn off Rhodes demo door hurt trigger
	sys.trigger($rhodesDoorDmg);	
}
void bombRoomTsd()
{
	// tsd's in the next room
	thread moveTsdFast($tube_tsd_36, 224);
	thread moveTsdFast($tube_tsd_37, 224);
	thread moveTsdFast($tube_tsd_38, 224);

	thread moveTsdSouth($tube_tsd_39, 224);
	thread moveTsdSouth($tube_tsd_40, 224);
	thread moveTsdSouth($tube_tsd_41, 224);
	thread moveTsdSouth($tube_tsd_42, 224);
	thread moveTsdSouth($tube_tsd_45, 224);

	thread moveTsdAngle($tube_tsd_43, $target_null_64, $target_null_65);
	thread moveTsdAngle($tube_tsd_44, $target_null_66, $target_null_67);
}
void rhodesDetonate()
{
	// do whatever you need to get him in the right pos, play any animations, blah
	// ...rhodes places the charge and gets out of the way
	sys.wait(1);

	$func_static_12001.setShaderParm(7, 0);	
	$door_typical_113.setShaderParm(7, 0);	

	//sys.println("release Rhodes");
	$Rhodes.setLeader($null_entity);
	aiSpeak( $Rhodes, "lipsync_vo_3_1_4_10_1" );	
	sys.trigger($rhodesPassive);
	sys.waitFrame();
	aiScriptedMoveWait( $Rhodes, $rhodesDemoDoor, 16, 1 );

	//sys.println("placeholder animation");
	aiScriptedAnimWait($Rhodes, "point_down", 4, 1);
	aiSpeak( $Rhodes, "lipsync_vo_3_1_4_10_2" );	
	
	aiScriptedMoveWait( $Rhodes, $rhodesClearDoor, 16, 1 );
	aiScriptedFaceWait ( $Rhodes, $door_typical_62, false );	

	// loop until player is out of the blast radius
	float fRhodesAnnoyanceLevel = 1;

	while ( 1 )
	{
		// if the distance from the detonation device to the player is less than whatever blast radius (400?? More? Less? ) you want, 
		//	scold the player
		// distance the player is from the door 
		if ( $door_typical_113.distanceTo( $player1 )  < 320 )
		{
			// Rhodes plays a scolding line, telling the player to get the heck out of the way
			aiSpeakWait( $Rhodes, "lipsync_vo_3_1_4_20_" + fRhodesAnnoyanceLevel );

			// bump rhodes up to the next level of annoyance, but don't go higher than 3
			fRhodesAnnoyanceLevel = fRhodesAnnoyanceLevel + 1;
			if ( fRhodesAnnoyanceLevel > 3 )
			{
				fRhodesAnnoyanceLevel = 3;
			}

			// wait a bit so the scolding lines don’t pile up and to give the player a chance to get out of the way
			sys.wait(1); 
		}
		else
		{
			// Rhodes does what he needs to to detonate the device 
			//	...rhodes blows the thing up
			aiScriptedAnim($Rhodes, "point_forward", 4, 1);
			sys.wait(1.25);
			sys.trigger($rhodesDoorFx);
			// toggle hurt trigger
			sys.trigger($rhodesDoorDmg);	
			sys.wait(.25);
			sys.trigger($rhodesDoorDmg);	
			sys.wait(.25);
			
			// unlock Rhodes exploding door.
			$func_static_12001.setShaderParm(7, 1);	
			$door_typical_113.setShaderParm(7, 1);		
			$door_typical_113.lock(0);
			
			//sys.println("setLeader for Rhodes, temp for right now.");
			$Rhodes.setLeader($player1);
			sys.trigger($rhodesAggressive);			
			aiSpeakWait( $Rhodes, "lipsync_vo_3_1_4_30_1" );
			
			break; // exit out of the while loop
		}
	}
}

void bigElevator()
{

	$Rhodes.setTalkState(TALK_WAIT);
	sys.wait(5);
	$Rhodes.lookAt($null_entity);
	aiSpeakWait( $Rhodes, "lipsync_vo_3_1_4_40_1" );
	sys.wait(10);
	aiSpeakWait( $Rhodes, "lipsync_vo_3_1_4_50_1" );
	sys.wait(7);	
	$Rhodes.lookAt($player1);
	aiSpeakWait( $Rhodes, "lipsync_vo_3_1_4_60_1" );
	$Rhodes.lookAt($null_entity);
}
/*------------------------------------------------

Radio chatter for storage1 second		mrenner

--------------------------------------------------*/
void heatSource()
{
	// "that heat source in the center"
	radioChatterPlayWait ($func_radiochatter_20, "");
}
void landingProcedure()
{
	// "commence landing procedure"
	radioChatterPlayWait ($func_radiochatter_21, "");
}
void beingDeployed()
{
	// "troops are being deployed"
	radioChatterPlayWait ($func_radiochatter_22, "");

	// "immediate dust off in..."
	radioChatterPlayWait ($func_radiochatter_23, "");
}
void wetCardboard()
{
	// "tore through the floor like wet cardboard"
	radioChatterPlayWait ($func_radiochatter_24, "");
}
void lightWeapons()
{
	// "light weapons don't hurt it."
	radioChatterPlayWait ($func_radiochatter_25, "");
}
void slowingDown()
{
	// "Nothing's slowing it down."
	radioChatterPlayWait ($func_radiochatter_26, "");
}
void concentrate()
{
	// "concentrate all fire on..."
	radioChatterPlayWait ($func_radiochatter_27, "");
}
void slaughteredHere()
{
	// "We're being slaughtered here"
	radioChatterPlayWait ($func_radiochatter_28, "");
}

void lightTanks()
{
	// kill the pilot reminder loop
	//sys.println("Kill pilot thread");
	sys.killthread( "map_storage1::pilotReminder");

	// thread heatSource();		// id/atvi notes	-mrenner

	$func_static_53912.setShaderParm(7, 0);
	$door_typical_148.setShaderParm(7, 0);
	$door_typical_148.lock(1);
}
void allSecondRadio()
{
	// "troops are being deployed"
	radioChatterPlayWait ($func_radiochatter_22, "");

	// "immediate dust off in..."
	radioChatterPlayWait ($func_radiochatter_23, "");
	
	// "We're being slaughtered here"
	//radioChatterPlayWait ($func_radiochatter_28, "");

	// "Where are you?"
	//thread rhodes2Radio();
	//aiSpeak( $Rhodes, "lipsync_vo_3_1_3_170_2" );		
	//radioChatterPlayWait ($func_radiochatter_30, "");
	
	// "light weapons don't hurt it."
	radioChatterPlayWait ($func_radiochatter_25, "");
	
	// "Nothing's slowing it down."
	radioChatterPlayWait ($func_radiochatter_26, "");
	
	// "concentrate all fire on..."
	radioChatterPlayWait ($func_radiochatter_27, "");
	
	// "Find me"
	thread rhodes2Radio();
	//aiSpeak( $Rhodes, "lipsync_vo_3_1_3_170_1" );		
	radioChatterPlayWait ($func_radiochatter_29, "");
	// meet rhodes objective
	sys.trigger($item_objective_4);
}

void startSlaughterRadio()
{
	thread allSecondRadio();	
}

void slaughter()
{
	// everyone almost dies.
	thread startSlaughterRadio();

	// turn on the cpr guys and all the models
	sys.trigger($cprMessTrig);
	
	$moveable_item_shotgun_1.show();
	$moveable_item_machinegun_1.show();
	
	$func_static_53912.setShaderParm(7, 1);
	$door_typical_148.setShaderParm(7, 1);
	$door_typical_148.lock(0);
}

//-----------------------------------------------------
// setupRubbleGrunt and startRubbleGrunt
//
// Prepares the rubble grunt, and animates his wakeup
// jshepard
//-----------------------------------------------------
void setupRubbleGrunt()	
{
	aiScriptedAnimLoop( $rubble_grunt_1, "storage_rubble_idle", 1);
}

void deadRubbleGrunt()
{
	sys.trigger($gruntCleanUp);
}
void startRubbleGrunt()	
{
	$rubble_clip.remove();
	
	
	$env_storage_rubble_on_creature_1.playAnim(ANIMCHANNEL_ALL, "rubble");
	
	aiScriptedAnimWait( $rubble_grunt_1, "storage_rubble", 1, 1);
	$rubble_grunt_1.setEnemy( $player1);
}
void randomPod01()
{
	//sys.println("random pod 1");
	//pod that travels from SE to NW
	$distantPodSnd01.time(12);

	sys.trigger($podCrash01Snd);
	$distantPodSnd01.moveTo($target_null_69);
	sys.waitFor($distantPodSnd01);
	sys.trigger($podCrash01Snd);

	$distantPodSnd01.time(.1);
	$distantPodSnd01.moveTo($target_null_68);
}
void randomPod02()
{
	//sys.println("random pod 2");
	//pod that travels from SW to NE
	$distantPodSnd02.time(12);

	sys.trigger($podCrash02Snd);
	$distantPodSnd02.moveTo($target_null_71);
	sys.waitFor($distantPodSnd02);
	sys.trigger($podCrash02Snd);

	$distantPodSnd02.time(.1);
	$distantPodSnd02.moveTo($target_null_70);
}
void loopPodCrashes()
{
	while(1)
	{
		sys.wait( 20 + sys.random(5) );	
		sys.trigger($podCrash02Snd);

		//	thread randomPod02();	
		sys.wait( 20 + sys.random(5) );	
		sys.trigger($podCrash01Snd);

		//	thread randomPod01();	
	}
}
/*------------------------------------------------

Radio chatter for storage1 first		mrenner

--------------------------------------------------*/
void radioNavComputer()
{
	// "Nav computer is screwed up.  I'm gonna crash."
	radioChatterPlayWait ($func_radiochatter_1, "");

	sys.trigger($podCrash01Snd);
	sys.wait(10);
	thread loopPodCrashes();
}
void radioPitchBlack()
{
	// "...it's pitch black in here.  Somebody tell me where I am."
	radioChatterPlayWait ($func_radiochatter_2, "");	
}
void radioHelpMe()
{
	// "someone get me out of this pod.  help me."
	radioChatterPlayWait ($func_radiochatter_3, "");	
}
void radioCaptMarin()
{
	// "located the pod containing captain marin's body."
	radioChatterPlayWait ($func_radiochatter_4, "");	
}
void radioRegroup()
{
	// "Hello marines at the Storage tower."
	radioChatterPlayWait ($func_radiochatter_5, "");	
	// "C'mon let's fine Hollenbeck"
/*	
	if($Shockley != $null_entity)
	{
		aiSpeakWait( $Shockley, "lipsync_2" );
	}
*/
	
	$Shockley.enableHeal();
	
	// Find Lt. Hollenbeck objective
	sys.trigger($item_objective_1);
}
void radioPodFire()
{
	// "My pod. It's on fire."
	radioChatterPlayWait ($func_radiochatter_6, "");	
}
void radioCobraSquad()
{
	// "HQ, this is cobra squad."
	radioChatterPlayWait ($func_radiochatter_7, "");	
}
void radioSeveredLeg()
{
	// "my left leg's been severed"
	radioChatterPlayWait ($func_radiochatter_8, "");	
}
void radioLevelBelow()
{
	// "I could use a hand here."
	radioChatterPlayWait ($func_radiochatter_9, "");	
	radioChatterPlayWait ($func_radiochatter_10, "");	
}
void radioMetalCoffins()
{
	// "I hate flying in those pods."
	radioChatterPlayWait ($func_radiochatter_11, "");	
}
void radioMainArmory()
{
	// "we've broken into the main armory"
	radioChatterPlayWait ($func_radiochatter_12, "");	
}
void radioDeepShit()
{
	// "Were in deep shit.  Send...aaahh!"
	radioChatterPlayWait ($func_radiochatter_13, "");	
}
void radioAccompanyKane()
{
	// "accompany Kane down to distribution."
	radioChatterPlayWait ($func_radiochatter_14, "");	
	radioChatterPlayWait ($func_radiochatter_15, "");	
}
void radioTrapped()
{
	// "trapped down in level 8"
	radioChatterPlayWait ($func_radiochatter_16, "");	
}
void allRadio()
{
	sys.wait( 5 + sys.random(2) );	
	sys.wait(2);
	// temp for now, but all will be in.
	thread radioRegroup();
	sys.wait( 20 + sys.random(5) );	
	thread radioNavComputer();
	sys.wait( 20 + sys.random(5) );	
	thread radioHelpMe();
	sys.wait( 20 + sys.random(5) );	
	thread radioCaptMarin();
	sys.wait( 20 + sys.random(5) );	
	thread radioPitchBlack();
	sys.wait( 20 + sys.random(5) );	
	thread radioPodFire();
	sys.wait( 20 + sys.random(5) );	
	thread radioCobraSquad();
	sys.wait( 20 + sys.random(5) );	
	thread radioLevelBelow();
	sys.wait( 20 + sys.random(5) );	
	thread radioMetalCoffins();
	sys.wait( 20 + sys.random(5) );	
	thread radioMainArmory();
}

void shaftWall()
{
	sys.wait(3);

	// temp function to look at the models 
	$shaftWallExitA.hide();
	$shaftWallEnterA.hide();
		
	$shaftWallExitB.show();
	$shaftWallEnterB.show();
		
	$shaftWallEnterC.hide();
	$shaftWallEnterC_ring1.hide();
	$shaftWallEnterC_ring2.hide();
	$shaftWallExitC.show();
}

void loopGruntPopper()
{
	aiScriptedAnimLoop ( $Shockley, "idle", 0 );
}
void popperMarine()
{
	$Shockley.setTalkState ( TALK_WAIT ); 
	aiScriptedAnimWait($Shockley, "step_on_grunt_MARINE", 4, 1);	

	// Shockley runs up to the player, then will follow tethers until he's dead.
	$Shockley.becomePassive(1);
	$Shockley.setMoveSpeed ( AIMOVESPEED_RUN );	

	aiScriptedMoveWait( $Shockley, $spotShockley, 16, 1 );
	$Shockley.lookAt($player1);
	aiSpeakWait( $Shockley, "lipsync_1" );
	$Shockley.setTalkState ( TALK_OK ); 
	
	$Shockley.setLeader($player1);
	
	thread allRadio();
}
void stepOn()
{
	//sys.println("grunt dies");
	aiScriptedAnim($dead_grunt_1, "storage_stepped_on", 4, 1);	
	sys.wait(1.5);
	$dead_grunt_1.kill();
	sys.wait(5);
	$grunt_smoke.remove();
}
void kill_grunt()
{
	sys.trigger($grunt_smoke);
	sys.trigger($dead_grunt_1);
	thread popperMarine();
}

void shockleyRun()
{
	// Shockley runs up to the player, then will follow tethers until he's dead.
	$Shockley.becomePassive(1);
	$Shockley.setMoveSpeed ( AIMOVESPEED_RUN );	
	$Shockley.setTalkState ( TALK_OK ); 
	aiScriptedMoveWait( $Shockley, $spotShockley, 16, 1 );
	$Shockley.lookAt($player1);
	aiSpeakWait( $Shockley, "lipsync_1" );

	$Shockley.setLeader($player1);
	
	thread allRadio();
}
void shockleyStop()
{
	$Shockley.setLeader($null_entity);
}
void playTubeCrashSnd()
{
	//sys.println("glass tubes");
	sys.trigger($breakingTubes);
}
void playExplode()
{
	//sys.println("splode");
	sys.trigger($func_fx_pod_explosion_1);
}
void gruntGrowl()
{
	//sys.println("Angry");
	sys.trigger($gruntGrowl);
}
void byeGrunt()
{
	$podCrashGrunt.kill();
//	sys.println("remove grunt");

}
void podGrunt()
{
//	aiScriptedAnimWait($podCrashGrunt, "droppod_crash_slow", 0, 1);
//	sys.println("play grunt");
	aiScriptedAnimWait($podCrashGrunt, "droppod_crash_slow", 0, 1);

//	sys.wait(3.5);
	
//	$podCrashGrunt.becomeRagdoll();	
//	$podCrashGrunt.remove();
}
void playGib()
{
	//sys.println("gib");
	sys.trigger($func_fx_pod_gib_1);
	sys.trigger($gruntPain);
}
void shaftWallA()
{
	//sys.println("wallA");
	$shaftWallEnterA.hide();
	$shaftWallEnterB.show();

	sys.trigger($func_fx_112);
	sys.waitFrame();
	sys.trigger($func_fx_115);
	sys.waitFrame();
	sys.trigger($fuzzyHead);
}
void shaftWallB()
{
	//sys.println("wallB");
	sys.trigger($fuzzyHead);
	sys.trigger($func_fx_113);
	sys.waitFrame();
	$shaftWallExitA.hide();
	$shaftWallExitB.show();
}
void shaftWallB_back()
{
	sys.trigger($func_fx_114);
	$shaftWallExitC.show();
	$shaftWallEnterC.hide();
	$shaftWallEnterC_ring1.hide();
	$shaftWallEnterC_ring2.hide();
}
void tubeHallA()
{
	sys.trigger($func_fx_116);
	$func_static_13008.show();
	$func_static_13009.show();
	$func_static_53997.hide();
	sys.waitFrame();
	sys.trigger($fuzzyHead);
}
void tubeHallB()
{
	sys.trigger($func_fx_89);
	$func_static_13016.show();
	$func_static_13015.show();
	$func_static_53998.hide();
	sys.wait(.5);
	sys.trigger($func_fx_88);
	sys.trigger($func_fx_59);
}
void lastWall()
{
	$func_static_53973.show();
	$func_static_53974.show();
	$func_static_54000.hide();
	$func_static_53999.hide();
	$func_static_53975.show();

	sys.trigger($fuzzyHead);

	sys.trigger($func_fx_117);
	sys.trigger($func_fx_110);

}
void stoppedHall()
{
	sys.trigger($func_fx_70);
	$func_static_53576.show();
	$func_static_13249.show();
	$func_static_54001.hide();
}

void turnOffSmoke()
{
	sys.wait(3);
	// turn off the smoke on the front of the pod
	sys.trigger($inFlightSmoke_2);
}
void hugeExplosionSound()
{
//	sys.wait(1);
	sys.trigger($hugeExplosion);
}
/*===============================================
Pod Crash for Storage1

mrenner
	
	envPod = the pod that the animations are played off of
	introCrashPod = the vehicle that the player is in, that is bound to introAnimPod
		
================================================*/
void bindStuff()
{
	$func_fx_pod_explosion_1.bindToJoint($introCrashPod, "body", 1);
	$func_fx_pod_gib_1.bindToJoint($introCrashPod, "body", 1);

	$podActivator.bindToJoint($introCrashPod, "body", 1);


	$gruntGrowl.bindToJoint($introCrashPod, "body", 1);
	$gruntPain.bindToJoint($introCrashPod, "body", 1);
	$crashPodSpeaker.bindToJoint($introCrashPod, "body", 1);
	$breakingTubes.bindToJoint($introCrashPod, "body", 1);
	$inFlightSmoke_2.bindToJoint($introCrashPod, "body", 1);
	$crashPodMover.bindToJoint($introCrashPod, "body", 1);
	$fuzzyHead.bindToJoint($introCrashPod, "body", 1);

}
void podCrash()
{
	thread turnOffSmoke();

	// hide the wrecked pod
	$stoppedPod.hide();
	$stoppedPod_door1.hide();
	$stoppedPod_door2.hide();

	// show the marine body inside the vehicle
	$introCrashPod.showSurface("models/monsters/tactical/tt_body");

	//sys.println("Into the building");
	
	$vehiclePodInFlight.lock(0);
	$player1.exitVehicle(1);

	sys.waitFrame();	
	
	// force the player into the vehicle
	$player1.enterVehicle($introCrashPod);
	
	// lock the player in the pod
	$introCrashPod.lock( true );	
	
	// bind the vehicle to the env
	$introCrashPod.bindToJoint($envPod, "body", 1);

	// bind the effects to the pod
	$func_fx_pod_explosion_1.bindToJoint($envPod, "body", 1);
	$func_fx_pod_gib_1.bindToJoint($envPod, "body", 1);

	// play the anim on the env...and start the sound
	sys.trigger( $crashPodSpeaker );
	thread hugeExplosionSound();
	$envPod.hide();
		
	$envPodInFlight.show();
	$envPodInFlight.playAnim(ANIMCHANNEL_ALL, "storage_crash");
			
	playAnimWait($envPod, ANIMCHANNEL_ALL, "storage_crash");	
	thread stoppedHall();

//	$envPod.hide();
	$envPodInFlight.hide();

	sys.fadeOut( '0 0 0', 1);	
	sys.wait(1);
	
	$crashPodMover.unbind();
	sys.waitFrame();
	$introCrashPod.bind($crashPodMover);
	$crashPodMover.time(.1);

	$introCrashPod.lock(0);
	$player1.exitVehicle(1);
	sys.waitFrame();
	// move the player to the starting position.
	$player1.setWorldOrigin( $storage1PlayerStart.getWorldOrigin());
	$player1.setViewAngles ( '0 180 0' );

	sys.wait(1);
//	thread shockleyRun();

	thread kill_grunt();

	$introCrashPod.remove();	
	sys.fadeIn( '1 1 1', 2);	

	$stoppedPod.show();
	$stoppedPod_door1.show();
	$stoppedPod_door2.show();	

	// turn on the main shaft beam
	sys.trigger( $func_fx_shaft_beam );
	sys.trigger( $func_fx_shaft_beam_1 );

}


/*------------------------------------------------
	START IN-FLIGHT POD CRASH
-------------------------------------------------*/
void buringPod01()
{
	$inFlightBurningPod99.playCycle(ANIMCHANNEL_ALL, "storage1_pod_skyfall_fast");
	sys.wait(.2);
	$inFlightBurningPod99_1.playCycle(ANIMCHANNEL_ALL, "storage1_pod_skyfall_fast");
	$inFlightBurningPod_1.playCycle(ANIMCHANNEL_ALL, "storage1_pod_skyfall_fast");

	$inFlightBurningPod02_2.playCycle(ANIMCHANNEL_ALL, "storage1_pod_skyfall_fast");
	sys.wait(.2);
	$inFlightBurningPod_2.playCycle(ANIMCHANNEL_ALL, "storage1_pod_skyfall_fast");

	$inFlightBurningPod_3.playCycle(ANIMCHANNEL_ALL, "storage1_pod_skyfall_fast");
	$inFlightBurningPod_4.playCycle(ANIMCHANNEL_ALL, "storage1_pod_skyfall_fast");
}

void flybyPod1()
{
	//sys.println("going down pod");
	setNewTimes( $inFlightBurningPod02_1 , 4 , 0 , 0 );

	sys.trigger($inFlightBurnFx_5);
	$inFlightBurningPod02_1.show();
	$inFlightBurningPod02_1.setAngles ('0 90 32');
	$inFlightBurningPod02_1.setWorldOrigin ($inflightPodSpline1.getWorldOrigin());		
	$inFlightBurningPod02_1.startSpline( $inflightPodSpline1 );
	sys.waitFor($inFlightBurningPod02_1);
	sys.trigger($inFlightBurnFx_5);
	$inFlightBurningPod02_1.hide();
}
void flybyPod2()
{
	setNewTimes( $inFlightBurningPod02_2_dummy , 12 , 4 , 6 );
	setNewTimes( $inFlightBurningPod02_2_dummy_1 , 12 , 4 , 4 );

	while(1)
	{
		$inFlightBurningPod02_2_dummy.move ( EAST, 256 );
		$inFlightBurningPod02_2_dummy_1.move ( EAST, 256 );
		sys.waitFor($inFlightBurningPod02_2_dummy);

		$inFlightBurningPod02_2_dummy.move ( WEST, 256 );
		$inFlightBurningPod02_2_dummy_1.move ( WEST, 256 );
		sys.waitFor($inFlightBurningPod02_2_dummy);	
	}
}
void burstFlames()
{
	sys.wait( 15 );
	//sys.println( "burning pod" );
	sys.trigger($inFlightFlak_10);
	sys.wait(1);
	sys.trigger($inFlightBurnFx_2);
	sys.wait(1);
	sys.trigger($inFlightBurnFx_2);
	sys.trigger($inFlightBurnFx_1);
	sys.wait(.2);
	sys.trigger( $inFlightBurnFx );
	
	sys.wait(5);
	setNewTimes( $inFlightBurningPod , 4 , 3 , 0 );
	sys.trigger($inFlightBurnFx_2);
	$inFlightBurningPod.setAngles ('0 65 25');
	$inFlightBurningPod.setWorldOrigin ($inflightPodSpline1_1.getWorldOrigin());		
	
	$inFlightBurningPod.startSpline( $inflightPodSpline1_1 );
	sys.waitFor($inFlightBurningPod);
	sys.trigger($bigPodExplosion);
	sys.trigger($bigPodShake);
	sys.trigger($blowUpPodSnd);

	sys.waitFrame();
	sys.wait(.2);
	
	$inFlightBurnFx.remove();
	$inFlightBurningPod.hide();

	sys.wait(.5);
	sys.trigger($podAlarmSnd);
	setNewTimes( $dummyPlayerPodMover , 10 , 10 , 0 );
	$dummyPlayerPodMover.move( UP, 256 );
}
void towerMove()
{
	setNewTimes( $fakeFacade , 30 , 20 , 0 );
	$fakeFacade.move( UP, 7500 );

	setNewTimes( $inFlightWall , 30 , 20 , 0 );
	$inFlightWall.move( SOUTH, 15000 );
}
void flakMover02()
{
	$inFlightFlakMover02.time(.5);

	while(1)
	{
		$inFlightFlakMover02.move( UP, 64 );
		sys.waitFor($inFlightFlakMover02);
		$inFlightFlakMover02.move( DOWN, 128 );
		sys.waitFor($inFlightFlakMover02);
		$inFlightFlakMover02.move( UP, 64 );
		sys.waitFor($inFlightFlakMover02);
	}
}
void flakMover01()
{
	thread flakMover02();

	while(1)
	{
		$inFlightFlakMover01.move( EAST, 96 );
		sys.waitFor($inFlightFlakMover01);
		$inFlightFlakMover01.move( WEST, 192 );
		sys.waitFor($inFlightFlakMover01);
		$inFlightFlakMover01.move( EAST, 96 );
		sys.waitFor($inFlightFlakMover01);
	}
}
void flak()
{
	while(1)
	{
		entity eEnt = $inFlight_flakNull.randomTarget("" );
		
		if ( isValidEntity(eEnt))
		{
			sys.trigger(eEnt);
		}

		sys.wait(sys.random(1));
	}
}
void tracerTarget02()
{
	$inFlightTracerMover02.time(.5);

	while(1)
	{
		$inFlightTracerMover02.move( UP, 16 );
		sys.waitFor($inFlightTracerMover02);
		$inFlightTracerMover02.move( DOWN, 32 );
		sys.waitFor($inFlightTracerMover02);
		$inFlightTracerMover02.move( UP, 16 );
		sys.waitFor($inFlightTracerMover02);
	}
}
void tracerTarget01()
{
	thread tracerTarget02();

	while(1)
	{
		$inFlightTracerMover01.move( EAST, 32 );
		sys.waitFor($inFlightTracerMover01);
		$inFlightTracerMover01.move( WEST, 64 );
		sys.waitFor($inFlightTracerMover01);
		$inFlightTracerMover01.move( EAST, 32 );
		sys.waitFor($inFlightTracerMover01);
	}
}

void bigGunFx01()
{
	while(1)
	{
		sys.wait( 4 + sys.random(3) );	
		sys.trigger($inFlightBigGun01);
		$inFlightBigShot01.time(2);
		$inFlightBigShot01.moveTo($inFlight_null_36);
		sys.waitFor($inFlightBigShot01);
		sys.trigger($inFlightBigGun01);
		sys.waitFrame();
		$inFlightBigShot01.time(.1);
		$inFlightBigShot01.moveTo($inFlight_null_38);
		sys.waitFor($inFlightBigShot01);
	}
}
void bigGunFx02()
{
	while(1)
	{
		sys.wait( 4 + sys.random(3) );	
		sys.trigger($inFlightBigGun02);
		$inFlightBigShot02.time(2);
		$inFlightBigShot02.moveTo($inFlight_null_37);
		sys.waitFor($inFlightBigShot02);
		sys.trigger($inFlightBigGun02);
		sys.waitFrame();
		$inFlightBigShot02.time(.1);
		$inFlightBigShot02.moveTo($inFlight_null_39);
		sys.waitFor($inFlightBigShot02);
	}
}
void radioFirstWave()
{
	// first wave is launched.
	radioChatterPlayWait ($firstWave, "");
}
void radioFunnyLook()
{
	// Hannibal doesn't look as damaged from here.
	radioChatterPlayWait ($funnyLook, "");
}
void radioAntiAircraft()
{
	// anti aircraft coming in from all directions
	radioChatterPlayWait ($antiAircraft, "");
}
void radioDeviate()
{
	// do not deviate from assigned flight plans
	radioChatterPlayWait ($doNotDeviate, "");
}
void radioGoingDown()
{
	// mayday, mayday, i'm hit.
	radioChatterPlayWait ($goingDown, "");
}
void radioLandingVectors()
{
	// the shields are affecting navigation
	radioChatterPlayWait ($landingVectors, "");
}
void radioFireSuppression()
{
	// there's a fire in my pod
	radioChatterPlayWait ($fireSuppression, "");
}
void radioFlyingBlind()
{
	// navigation is down.
	radioChatterPlayWait ($flyingBlind, "");
}
void allinFlightRadio()
{
	radioChatterPlayWait ($firstWave, "");
	radioChatterPlayWait ($funnyLook, "");
	radioChatterPlayWait ($antiAircraft, "");
	radioChatterPlayWait ($doNotDeviate, "");
	thread flybyPod1();
	radioChatterPlayWait ($goingDown, "");
	radioChatterPlayWait ($landingVectors, "");
	radioChatterPlayWait ($fireSuppression, "");
	radioChatterPlayWait ($flyingBlind, "");
}
void playerPodBurns()
{
	sys.trigger($inFlightFlak_11);
	sys.trigger($fuzzyHead);
	sys.wait(.5);
	sys.trigger($inFlightBurnFx_3);
	sys.wait(.5);
	sys.trigger($inFlightBurnFx_4);
	sys.wait(.25);
	sys.trigger($fuzzyHead);
	sys.trigger($inFlightSmoke);
	sys.trigger($inFlightSmoke_2);
	sys.trigger($inFlightSmoke_1);
	
//	sys.wait(1);
	thread podCrash();
}
void airAssault()
{
	setNewTimes( $fakeFacade , .1 , 0 , 0 );
	$fakeFacade.move( DOWN, 7500 );

	aiScriptedAnimLoop($vehiclePodInFlight, "storage1_pod_skyfall", 4);
	$envPodInFlight.hide();

	thread bigGunFx01();
	thread bigGunFx02();
	thread flak();
	thread tracerTarget01();

	sys.trigger($inFlightStartTracers);

	thread buringPod01();
	thread flybyPod2();
	sys.fadeIn( '1 1 1', 5);
	sys.wait(2);
	thread allinFlightRadio();
	
	thread burstFlames();

	thread towerMove();

	setNewTimes( $inFlightBurningPod02 , 40 , 15 , 0 );
	$inFlightBurningPod02.moveTo($inFlight_null_42);

	setNewTimes( $inFlightBurningPod02_3 , 40 , 25 , 0 );
	$inFlightBurningPod02_3.moveTo($inFlight_null_44);
}

void inFlightSetup()
{
	thread airAssault();

	// show the marine body inside the vehicle
	$vehiclePodInFlight.showSurface("models/monsters/tactical/tt_body");
	
	// force the player into the vehicle
	$player1.enterVehicle($vehiclePodInFlight);
	
	// lock the player in the pod
	$vehiclePodInFlight.lock( true );	
	
	// bind the vehicle to the env
	$vehiclePodInFlight.bindToJoint($envPodInFlight, "body", 1);
		
	sys.wait(30);
	thread playerPodBurns();
	
	sys.wait(1);
	
	sys.killthread( "map_storage1::bigGunFx01");	
	sys.killthread( "map_storage1::bigGunFx02");	
	sys.killthread( "map_storage1::flak");	
	sys.killthread( "map_storage1::tracerTarget01");	

}
/*------------------------------------------------
	END IN-FLIGHT POD CRASH
-------------------------------------------------*/
void mainShaftSetup()
{
	$shaftWallEnterB.show();
	$shaftWallExitB.show();
	
	$shaftWallExitA.hide();
	$shaftWallEnterA.hide();
}
void seeHollenbeck()
{
	sys.trigger($Hollenbeck);
	aiScriptedAnimWait($Hollenbeck, "idle_wrist_gui_start_fast", 4, 1);
	aiScriptedAnimLoop($Hollenbeck, "idle_wrist_gui_loop", 4);

	aiSpeakWait( $Hollenbeck, "lipsync_1" );
	sys.trigger($morrisRadio01);
	sys.wait(3.25);
	aiSpeakWait( $Hollenbeck, "lipsync_2" );
	sys.trigger($meetHollenbeckTrig);
	aiScriptedAnimWait($Hollenbeck, "idle_wrist_gui_end_fast", 4, 1);
}
void meetHollenbeck()
{
	// Find Lt. Hollenbeck objective complete.
	sys.trigger($item_objectivecomplete_1);

	$Hollenbeck.lookAt($player1);
	$Hollenbeck.setTalkState(TALK_OK);	
	aiSpeakWait( $Hollenbeck, "lipsync_3" );
	
	// Reactivate TSD's
	sys.trigger($item_objective_2);
}
void nextLevel()
{
	sys.fadeOut( '0 0 0', 2);
	sys.wait(.5);
	sys.trigger($endLevel);
}
void endLevelSecond()
{
	// radio chatter heard between Cortez and Morris
	
	// "Do you read me?"
	radioChatterPlayWait ($cortezRadio_1, "");
	sys.wait(1);

	// "Go ahead"
	radioChatterPlayWait ($morrisRadio_1, "");
	
	// "hijacked a tram"
	radioChatterPlayWait ($cortezRadio_2, "");
	
	// "proceed to process"
	radioChatterPlayWait ($morrisRadio_2, "");
	
	// "tracks have been destroyed"
	radioChatterPlayWait ($cortezRadio_3, "");

	// "morris out."
	//radioChatterPlayWait ($morrisRadio_3, "");
	sys.trigger($morrisRadio_3);
	sys.wait(2);

	sys.fadeOut( '0 0 0', 3);
	sys.wait(3);
	//sys.println("end level triggered");
	sys.trigger($target_endlevel_2);
}
void activateExitLift()
{
	$func_elevator_34.hide();
	$func_static_54039.show();
	//$func_elevator_34.setGuiParm( "gui_parm_disable", "0" );
}

void sidekicks()
{
	$Rutger.setTalkState(TALK_OK);	
	$Mills.setTalkState(TALK_OK);
	$Rutger.lookAt($player1);
	$Mills.lookAt($player1);
	aiSpeakWait( $Rutger, "lipsync_1" );
	aiSpeakWait( $Mills, "lipsync_1" );
	$Rutger.enableHeal();
}
void torsoPumps()
{
	$torsoPump_1.playCycle(ANIMCHANNEL_ALL, "idle");
	sys.wait(.3);
	$torsoPump_2.playCycle(ANIMCHANNEL_ALL, "idle");
	
//	aiScriptedMoveWait( $Rhodes, $upperRhodesElevator, 20, 0 );
}
void elevatorGrunt()
{
	sys.trigger($ai_trigger_once_5);
//	aiScriptedAnimLoop( $monster_grunt_10, "idle", 0 );
	sys.wait(30);

	// triggering the tethers to force the grunt from the elevator and the release him.
	sys.trigger($ai_tether_radius_26);
	sys.trigger($ai_trigger_once_4);
}

void elevatorWaitingSnd()
{
	while(1)
	{
		sys.trigger($waitingForElevator);
		sys.wait(6);
	}
}
void gruntDead()
{
	$monster_grunt_10.becomeNonSolid();	

	sys.trigger($rhodesPassive);
}
void randomDebris()
{
	while(1)
	{
		sys.trigger($func_fx_540);
		sys.wait( 5 + sys.random(5) );		
		sys.trigger($func_fx_541);
		sys.wait( 5 + sys.random(5) );		
		sys.trigger($func_fx_542);
		sys.wait( 5 + sys.random(5) );		
		sys.trigger($func_fx_543);
		sys.wait( 5 + sys.random(5) );		
	}
}

void switchRoofElevatorsBottom()
{
	//$func_elevator_36.setKey("gui_parm_disable", "0"); // the gui can't be clicked until this is set back to 0
	
	//$func_elevator_36.setGuiParm("noninteractive", "0"); // the gui can't be clicked until this is set back to 0
}
void switchRoofElevatorsTop()
{
	//$func_elevator_36.setKey("gui_parm_disable", "1"); // the gui can't be clicked until this is set back to 0
	
	//$func_elevator_36.setGuiParm("noninteractive", "1"); // the gui can't be clicked until this is set back to 0
}

void swapElevator()
{
	//$func_elevator_9.setKey("gui_parm_disable", "1"); // the gui can't be clicked until this is set back to 0

//	$func_elevator_9.hide();
//	$fakeTopElevator.show();
	//sys.println("Not used?");
}
void tallElevator()
{
	thread randomDebris();

	//sys.println("Move elevator down");
	sys.trigger($monster_grunt_10);

	// turn on the spawner and the tether, activate the trigger to turn it off.
	sys.trigger($trigger_once_101);
	sys.trigger($func_spawner_1);
	sys.trigger($ai_tether_radius_27);
	
	// tether Rhodes to the room.
	sys.trigger($ai_tether_radius_28);

	thread elevatorWaitingSnd();
}
void tallElevatorDown()
{
//	$fakeTopElevator.show();
//	$func_elevator_9.hide();

	//$func_elevator_9.setKey("gui_parm_disable", "1"); // the gui can't be clicked until this is set back to 0

	//sys.println("Kill sound");
	sys.killthread( "map_storage1::elevatorWaitingSnd");
}

void tallElevatorGood()
{
	//sys.println("enable the GUI");

	//$func_elevator_9.setKey("gui_parm_disable", "0"); // the gui can't be clicked until this is set back to 0

	$tallElevatorClip.show();

//	$fakeTopElevator.hide();
//	$func_elevator_9.show();
}
void clipTallElevator()
{
	//sys.println("close door");
	$tallElevatorClip.show();
}

void dmgArmEastLower()
{
	setNewTimes( $dmgPivotEast_1 , .25 , 0 , .25 );
	$dmgPivotEast_1.rotateOnce('-25 0 0');	
	sys.waitFor($dmgPivotEast_1);

	setNewTimes( $dmgPivotEast_1 , .5 , 0 , .5 );
	setNewTimes( $dmgPivotEast_2 , .5 , 0 , .5 );
	setNewTimes( $dmgPivotEast_3 , .5 , 0 , .5 );
	setNewTimes( $dmgPivotEast_4 , .5 , 0 , .5 );
	
	$dmgPivotEast_1.rotateOnce('90 0 0');	
	$dmgPivotEast_2.rotateOnce('87 0 0');	
	$dmgPivotEast_3.rotateOnce('90 0 0');	
	sys.waitFor($dmgPivotEast_1);

	$dmgPivotEast_1.rotateOnce('0 0 180');	
	$dmgPivotEast_2.rotateOnce('45 0 0');	
	$dmgPivotEast_3.rotateOnce('20 0 0');	
	sys.waitFor($dmgPivotEast_1);

	$dmgPivotEast_1.rotateOnce('110 0 0');	
	$dmgPivotEast_2.rotateOnce('-90 0 0');	
	$dmgPivotEast_3.rotateOnce('-90 0 0');	
	$dmgPivotEast_4.rotateOnce('75 0 0');		
	sys.waitFor($dmgPivotEast_1);

	setNewTimes( $dmgPivotEast_1 , .1 , 0 , .1 );
	$dmgPivotEast_1.rotateOnce('-20 0 0');	
	
}
void dmgArmEastRaise()
{
	setNewTimes( $dmgPivotEast_1 , .1 , 0 , .1 );
	setNewTimes( $dmgPivotEast_2 , .1 , 0 , .1 );
	setNewTimes( $dmgPivotEast_3 , .1 , 0 , .1 );
	setNewTimes( $dmgPivotEast_4 , .1 , 0 , .1 );
	$dmgPivotEast_1.rotateOnce('10 0 0');	
	$dmgPivotEast_2.rotateOnce('10 0 0');	
	$dmgPivotEast_3.rotateOnce('10 0 0');	
	$dmgPivotEast_4.rotateOnce('-10 0 0');		
	sys.waitFor($dmgPivotEast_1);

	setNewTimes( $dmgPivotEast_1 , 1 , 0 , .5 );
	setNewTimes( $dmgPivotEast_2 , 1 , 0 , .5 );
	setNewTimes( $dmgPivotEast_3 , 1 , 0 , .5 );
	setNewTimes( $dmgPivotEast_4 , 1 , 0 , .5 );
	$dmgPivotEast_1.rotateOnce('35 0 0');	
	$dmgPivotEast_2.rotateOnce('60 0 0');	
	$dmgPivotEast_3.rotateOnce('60 0 0');	
	$dmgPivotEast_4.rotateOnce('-65 0 0');		
	sys.waitFor($dmgPivotEast_1);

	setNewTimes( $dmgPivotEast_1 , 1 , .5 , .5 );
	setNewTimes( $dmgPivotEast_2 , 1 , .5 , .5 );
	setNewTimes( $dmgPivotEast_3 , 1 , .5 , .5 );
	$dmgPivotEast_1.rotateOnce('90 0 0');	
	$dmgPivotEast_2.rotateOnce('-90 0 0');	
	$dmgPivotEast_3.rotateOnce('-90 0 0');	
	sys.waitFor($dmgPivotEast_1);
}
void dmgArmEastSetup()
{
	setNewTimes( $dmgPivotEast_1 , .1 , 0 , 0 );
	setNewTimes( $dmgPivotEast_2 , .1 , 0 , 0 );
	setNewTimes( $dmgPivotEast_3 , .1 , 0 , 0 );
	setNewTimes( $dmgPivotEast_3 , .1 , 0 , 0 );

	$dmgPivotEast_1.rotateOnce('-90 0 0');	
	$dmgPivotEast_2.rotateOnce('90 0 0');	
	$dmgPivotEast_3.rotateOnce('90 0 0');	
	$dmgPivotEast_4.rotateOnce('-75 0 0');		
	sys.waitFor($dmgPivotEast_1);
	$dmgPivotEast_1.rotateOnce('0 0 -180');	
	$dmgPivotEast_2.rotateOnce('-45 0 0');	
	$dmgPivotEast_3.rotateOnce('-20 0 0');	
	sys.waitFor($dmgPivotEast_1);
	$dmgPivotEast_1.rotateOnce('-90 0 0');	
	$dmgPivotEast_2.rotateOnce('-87 0 0');	
	$dmgPivotEast_3.rotateOnce('-90 0 0');	
	sys.waitFor($dmgPivotEast_1);
	$dmgPivotEast_1.rotateOnce('25 0 0');	
	sys.waitFor($dmgPivotEast_1);
}

void dmgArmWestLower()
{
	setNewTimes( $dmgPivotWest_1 , .25 , 0 , .25 );
	$dmgPivotWest_1.rotateOnce('25 0 0');	
	sys.waitFor($dmgPivotWest_1);

	setNewTimes( $dmgPivotWest_1 , .5 , 0 , .5 );
	setNewTimes( $dmgPivotWest_2 , .5 , 0 , .5 );
	setNewTimes( $dmgPivotWest_3 , .5 , 0 , .5 );
	setNewTimes( $dmgPivotWest_4 , .5 , 0 , .5 );
	
	$dmgPivotWest_1.rotateOnce('-90 0 0');	
	$dmgPivotWest_2.rotateOnce('-87 0 0');	
	$dmgPivotWest_3.rotateOnce('-90 0 0');	
	sys.waitFor($dmgPivotWest_1);

	$dmgPivotWest_1.rotateOnce('0 0 180');	
	$dmgPivotWest_2.rotateOnce('-45 0 0');	
	$dmgPivotWest_3.rotateOnce('-20 0 0');	
	sys.waitFor($dmgPivotWest_1);

	$dmgPivotWest_1.rotateOnce('-110 0 0');	
	$dmgPivotWest_2.rotateOnce('90 0 0');	
	$dmgPivotWest_3.rotateOnce('90 0 0');	
	$dmgPivotWest_4.rotateOnce('-75 0 0');		
	sys.waitFor($dmgPivotWest_1);

	setNewTimes( $dmgPivotWest_1 , .1 , 0 , .1 );
	$dmgPivotWest_1.rotateOnce('20 0 0');	
}
void dmgArmWestRaise()
{
	setNewTimes( $dmgPivotWest_1 , .1 , 0 , .1 );
	setNewTimes( $dmgPivotWest_2 , .1 , 0 , .1 );
	setNewTimes( $dmgPivotWest_3 , .1 , 0 , .1 );
	setNewTimes( $dmgPivotWest_4 , .1 , 0 , .1 );
	$dmgPivotWest_1.rotateOnce('-10 0 0');	
	$dmgPivotWest_2.rotateOnce('-10 0 0');	
	$dmgPivotWest_3.rotateOnce('-10 0 0');	
	$dmgPivotWest_4.rotateOnce('10 0 0');		
	sys.waitFor($dmgPivotWest_1);

	setNewTimes( $dmgPivotWest_1 , 1 , 0 , .5 );
	setNewTimes( $dmgPivotWest_2 , 1 , 0 , .5 );
	setNewTimes( $dmgPivotWest_3 , 1 , 0 , .5 );
	setNewTimes( $dmgPivotWest_4 , 1 , 0 , .5 );
	$dmgPivotWest_1.rotateOnce('-35 0 0');	
	$dmgPivotWest_2.rotateOnce('-60 0 0');	
	$dmgPivotWest_3.rotateOnce('-60 0 0');	
	$dmgPivotWest_4.rotateOnce('65 0 0');		
	sys.waitFor($dmgPivotWest_1);

	setNewTimes( $dmgPivotWest_1 , 1 , .5 , .5 );
	setNewTimes( $dmgPivotWest_2 , 1 , .5 , .5 );
	setNewTimes( $dmgPivotWest_3 , 1 , .5 , .5 );
	$dmgPivotWest_1.rotateOnce('-90 0 0');	
	$dmgPivotWest_2.rotateOnce('90 0 0');	
	$dmgPivotWest_3.rotateOnce('90 0 0');	
	sys.waitFor($dmgPivotWest_1);
}
void dmgArmWestSetup()
{
	setNewTimes( $dmgPivotWest_1 , .1 , 0 , 0 );
	setNewTimes( $dmgPivotWest_2 , .1 , 0 , 0 );
	setNewTimes( $dmgPivotWest_3 , .1 , 0 , 0 );
	setNewTimes( $dmgPivotWest_3 , .1 , 0 , 0 );

	$dmgPivotWest_1.rotateOnce('90 0 0');	
	$dmgPivotWest_2.rotateOnce('-90 0 0');	
	$dmgPivotWest_3.rotateOnce('-90 0 0');	
	$dmgPivotWest_4.rotateOnce('75 0 0');		
	sys.waitFor($dmgPivotWest_1);
	$dmgPivotWest_1.rotateOnce('0 0 -180');	
	$dmgPivotWest_2.rotateOnce('45 0 0');	
	$dmgPivotWest_3.rotateOnce('20 0 0');	
	sys.waitFor($dmgPivotWest_1);
	$dmgPivotWest_1.rotateOnce('90 0 0');	
	$dmgPivotWest_2.rotateOnce('87 0 0');	
	$dmgPivotWest_3.rotateOnce('90 0 0');	
	sys.waitFor($dmgPivotWest_1);
	$dmgPivotWest_1.rotateOnce('-25 0 0');	
	sys.waitFor($dmgPivotWest_1);
}

void dmgPulse()
{
	while(1)
	{
		sys.trigger($dmglightsDown);
		sys.wait(4);
	}
}
void dmgTurns()
{
	while(1)
	{
		$dmgRings.rotateOnce('0 90 0');		
		sys.waitFor($dmgRings);
	}
}
void dmgRings()
{
	setNewTimes( $outerRings , 1 , 0 , 0 );
	setNewTimes( $middleRings , 1 , 0 , 0 );
	setNewTimes( $innerRings , 1 , 0 , 0 );

	while(1)
	{
		$outerRings.rotateOnce('0 0 360');	
		$middleRings.rotateOnce('0 360 0');	
		$innerRings.rotateOnce('0 0 180');	
		sys.waitFor($outerRings);
	}
}
void unbindRings()
{
	$outerRingsRight.unbind();
	$middleRingsRight.unbind();
	$innerRingsRight.unbind();
	$outerRingsLeft.unbind();
	$middleRingsLeft.unbind();
	$innerRingsLeft.unbind();
	sys.waitFrame();
	$outerRingsRight.bind($func_mover_12236);
	$middleRingsRight.bind($func_mover_12236);
	$innerRingsRight.bind($func_mover_12236);
	$outerRingsLeft.bind($func_mover_12232);
	$middleRingsLeft.bind($func_mover_12232);
	$innerRingsLeft.bind($func_mover_12232);
}
void stopRings()
{
	thread dmgArmWestLower();
	dmgArmEastLower();

	sys.killthread( "map_storage1::dmgRings");
	sys.killthread( "map_storage1::dmgPulse");

	sys.wait(1);
	setNewTimes( $middleRings , .25 , 0 , 0 );
	$middleRings.rotateOnce('90 0 0');	
	sys.waitFor($middleRings);

	unbindRings();
	
	$dmgClip.hide();

	thread dmgArmWestRaise();
	thread dmgArmEastRaise();
	
	$func_fx_132.remove();
	sys.trigger($dmgImpact);
}
void dmgSetup()
{
	thread dmgArmWestSetup();
	thread dmgArmEastSetup();
	
	thread dmgPulse();
	thread dmgTurns();
	
	thread dmgRings();
}
void dmgSetup2()
{
	setNewTimes( $middleRings , .1 , 0 , 0 );
	$middleRings.rotateOnce('90 0 0');	
	sys.waitFor($middleRings);
	unbindRings();
	thread dmgArmWestRaise();
	thread dmgArmEastRaise();
}

void enterDmgRoom()
{
	// Lock the player into the room.
	$func_static_53823.setShaderParm(7, 0);
	$door_typical_143.setShaderParm(7, 0);
	$door_typical_143.lock(1);

	$func_static_53821.setShaderParm(7, 0);
	$door_typical_142.setShaderParm(7, 0);
	$door_typical_142.lock(1);

	$func_static_53829.setShaderParm(7, 0);
	$door_typical_144.setShaderParm(7, 0);
	$door_typical_144.lock(1);
}
void doneDmg()
{
	// Lock the player into the room.
	$func_static_53823.setShaderParm(7, 1);
	$door_typical_143.setShaderParm(7, 1);
	$door_typical_143.lock(0);

	$func_static_53821.setShaderParm(7, 1);
	$door_typical_142.setShaderParm(7, 1);
	$door_typical_142.lock(0);

	$func_static_53829.setShaderParm(7, 1);
	$door_typical_144.setShaderParm(7, 1);
	$door_typical_144.lock(0);
}
void gotDmg()
{
	//sys.println("DMG!");

	// unLock a door.
	$func_static_53823.setShaderParm(7, 1);
	$door_typical_143.setShaderParm(7, 1);
	$door_typical_143.lock(0);
}
void trigBotCount()
{
	// trigger the counter to fire off the 
	sys.trigger($deadBots);
}
void tossCamera()
{
	sys.trigger($fakeCameraFx);
	setNewTimes($fakeCamRotate_1, .1, 0, .1);
	$fakeCamRotate_1.rotateOnce('0 115 0');
	sys.wait(.1);
	$fakeCamBrokeScreen.show();
	$fakeCamGoodScreen.hide();
	
	sys.wait(3);
	sys.trigger($fakeCamCleanUp);
}
void fakeCamera()
{
	//sys.println("Go fakeCamera");
	aiScriptedAnim($dummyGuardian, "melee_attack1", 4, 1);	
	
	sys.wait(.8);
	thread tossCamera();

}
void rhodesTesting()
{
	//sys.println("move Rhodes");
	sys.trigger($Rhodes);

	// move the rhodes to the testing position.
	$Rhodes.setWorldOrigin( $target_null_89.getWorldOrigin());
	$Rhodes.setAngles ( '0 180 0' );

}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////Chad Additions///////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Only enables the exit lift GUI if the player is on the lift.  Stops them from peeking around and pressing the GUI without getting on.
void enable_exit_gui()
{
	$exit_elevator.setKey("gui_parm_disable", "0");
	$exit_elevator.setGuiParm("noninteractive", "0"); // the gui can't be clicked until this is set back to 0
}

//Mission fails if Rhino Squad member dies.
void rhodes_death()
{
	sys.trigger($rhodes_died);
}

void disable_long_lift()
{
	$func_elevator_9.setKey("gui_parm_disable", "1");

	$func_elevator_9.setGuiParm("noninteractive", "1"); // the gui can't be clicked until this is set back to 0
	
	$Rhodes.setTalkState(TALK_OK); 
}

void enable_long_lift()
{
	//sys.println("enable the GUI");
	
	$func_elevator_9.setKey("gui_parm_disable", "0");

	$func_elevator_9.setGuiParm("noninteractive", "0"); // the gui can't be clicked until this is set back to 0
}

void enable_elevator_36()
{
	//sys.println("Enable da GUI");

	$func_elevator_36.setKey("gui_parm_disable", "0");

	$func_elevator_36.setGuiParm("noninteractive", "0"); // the gui can't be clicked until this is set back to 0
}

//-----------------------------------------------------
// Main:
//
// Sets up parameters and checks for pod crash launch.
//
// cbordwell & jshepard & mrenner(changed the script to have first and second pass)
//-----------------------------------------------------
void main()
{
	// sound used by firedoors, must be cached 
	$player1.cacheSoundShader("storage_firedoor_open");

	if(sys.getcvar("si_entityFilter") == "first")

	{
		//sys.println("Start Storage1 First");
		// player enters the level by crashing his pod into the level.
		sys.sendNamedEvent( GUI_PLAYERHUD, "showHud" );
		thread inFlightSetup();
		
		thread bentHallwaySetup();
		
		thread dmgSetup();
	}

	// If no filter specified, or filter two, use this.

	else
	{
		//sys.println("Start Storage1 Second");
		// shoosh, moire, you're having CPR done to you!
		$Moire.setTalkState ( TALK_NEVER ); 

		// player enters the level from the TSD storage area below.
		thread pathSecond();
		
		// setup the destroyed shaft wall
		thread mainShaftSetup();
		
		// tsd's in the main elevator room
		thread introTsds();

		// set up the jet pack effects 3/25/05 gc
		thread initNetworkGuardian();

		// set in motion crashpods for this segment
//		thread doAmbientElevatorCrashPods();

		// we can turn on the main shaft beam at the start for the second pass...
		//	just hidden in first pass for the crash sequence
		sys.trigger( $func_fx_shaft_beam );
		sys.trigger( $func_fx_shaft_beam_1 );		

		// retract arms into the ceiling.
		thread dmgSetup2();
		
		$guardianBox_1.bind($func_mover_11977);
		$guardianBox_2.bind($func_mover_11977);
		$guardianBox_3.bind($func_mover_11977);

		$exit_elevator.setGuiParm("noninteractive", "1"); // the gui can't be clicked until this is set back to 0

		$second_lift.guiEvent ( "anim_up" );
		
		$trigger_hurt_28.bindToJoint($daredevilDropship, "still", 1);
		$ship_clip.bindToJoint($daredevilDropship, "still", 1);
		
		$ship_floor.bindToJoint($daredevilDropship, "still", 1);
		strogg_dropship::bindMonsters($daredevilDropship);

		$laser_coupling_1.playCycle(ANIMCHANNEL_ALL, "spin_loop_slow");

		// the beam cannon on the roof.
		thread beamSetup();
		
		thread disable_long_lift();
		
		$func_elevator_36.setKey("gui_parm_disable", "1"); // the gui can't be clicked until this is set back to 0
		$func_elevator_36.setGuiParm("noninteractive", "1"); // the gui can't be clicked until this is set back to 0

		// What was I thinking.
		$bridge_gui_2.hide();
	}

	// This stuff will happen everytime you visit the storage1.

	// the gui that controls the central bridge
		thread gui_in();
	
	// the central bridge that the player will eventually cross
		thread bridge_setup();
		
	// the main beam moving bit.
		thread mainBeamTop();
}

//end namespace
}